package cc.orbexa.hhy.chat

// Generated by scripts/generate_chat_report_reason_catalog.py. Do not edit.
internal val R14_CHAT_REPORT_REASONS: List<R14ReportReasonOption> = listOf(
    R14ReportReasonOption(code = "HARASSMENT", label = "骚扰"),
    R14ReportReasonOption(code = "DUPLICATE_BULK_MESSAGE", label = "相同文案批量发送"),
    R14ReportReasonOption(code = "DANGEROUS_LINK", label = "危险链接"),
)
