// Generated from database/enum_registry.yaml. Do not edit.

export type ContentStatus = "DRAFT" | "PENDING_REVIEW" | "REVIEWING" | "REJECTED" | "APPROVED" | "ONLINE" | "OFFLINE_BY_OWNER" | "OFFLINE_BY_PLATFORM" | "RECTIFICATION" | "BANNED" | "DELETED";
export const ContentStatusValues = ["DRAFT", "PENDING_REVIEW", "REVIEWING", "REJECTED", "APPROVED", "ONLINE", "OFFLINE_BY_OWNER", "OFFLINE_BY_PLATFORM", "RECTIFICATION", "BANNED", "DELETED"] as const;

export type RedPacketStatus = "DRAFT" | "PRE_REVIEWING" | "PRE_REVIEW_REJECTED" | "PRE_REVIEW_APPROVED" | "WAITING_PAYMENT" | "PAYMENT_PROCESSING" | "ACTIVE" | "PAUSED_BY_CONTENT_OFFLINE" | "PAUSED_BY_OWNER" | "PAUSED_BY_RISK" | "SOLD_OUT" | "CLOSED_BY_OWNER" | "TERMINATED_BY_PLATFORM";
export const RedPacketStatusValues = ["DRAFT", "PRE_REVIEWING", "PRE_REVIEW_REJECTED", "PRE_REVIEW_APPROVED", "WAITING_PAYMENT", "PAYMENT_PROCESSING", "ACTIVE", "PAUSED_BY_CONTENT_OFFLINE", "PAUSED_BY_OWNER", "PAUSED_BY_RISK", "SOLD_OUT", "CLOSED_BY_OWNER", "TERMINATED_BY_PLATFORM"] as const;

export type OrderStatus = "PENDING_PAYMENT" | "PAYMENT_PROCESSING" | "PAID" | "FULFILLING" | "COMPLETED" | "PAYMENT_FAILED" | "CLOSED" | "CHANNEL_REVERSAL";
export const OrderStatusValues = ["PENDING_PAYMENT", "PAYMENT_PROCESSING", "PAID", "FULFILLING", "COMPLETED", "PAYMENT_FAILED", "CLOSED", "CHANNEL_REVERSAL"] as const;

export type RewardStatus = "PENDING_SETTLEMENT" | "AVAILABLE" | "RISK_FROZEN" | "WITHDRAWAL_FROZEN" | "WITHDRAWN" | "REVERSED";
export const RewardStatusValues = ["PENDING_SETTLEMENT", "AVAILABLE", "RISK_FROZEN", "WITHDRAWAL_FROZEN", "WITHDRAWN", "REVERSED"] as const;

export type WithdrawalStatus = "CREATED" | "RISK_REVIEWING" | "FINANCE_REVIEWING" | "APPROVED" | "PAYOUT_PROCESSING" | "SUCCEEDED" | "FAILED" | "REJECTED" | "CANCELLED";
export const WithdrawalStatusValues = ["CREATED", "RISK_REVIEWING", "FINANCE_REVIEWING", "APPROVED", "PAYOUT_PROCESSING", "SUCCEEDED", "FAILED", "REJECTED", "CANCELLED"] as const;

export type IdentityStatus = "NOT_STARTED" | "SESSION_CREATED" | "LIVENESS_PENDING" | "PROVIDER_PROCESSING" | "MANUAL_REVIEW" | "VERIFIED" | "REJECTED" | "EXPIRED";
export const IdentityStatusValues = ["NOT_STARTED", "SESSION_CREATED", "LIVENESS_PENDING", "PROVIDER_PROCESSING", "MANUAL_REVIEW", "VERIFIED", "REJECTED", "EXPIRED"] as const;

export type MembershipPlan = "NORMAL" | "MONTH" | "QUARTER" | "YEAR";
export const MembershipPlanValues = ["NORMAL", "MONTH", "QUARTER", "YEAR"] as const;

export type TrafficType = "ORGANIC_TRAFFIC" | "INCENTIVIZED_RED_PACKET_TRAFFIC" | "INCENTIVIZED_TASK_TRAFFIC";
export const TrafficTypeValues = ["ORGANIC_TRAFFIC", "INCENTIVIZED_RED_PACKET_TRAFFIC", "INCENTIVIZED_TASK_TRAFFIC"] as const;

export type BuildJobStatus = "QUEUED" | "PREPARING" | "BUILDING" | "TESTING" | "SIGNING" | "UPLOADING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
export const BuildJobStatusValues = ["QUEUED", "PREPARING", "BUILDING", "TESTING", "SIGNING", "UPLOADING", "SUCCEEDED", "FAILED", "CANCELLED"] as const;

export type ConfigVersionStatus = "DRAFT" | "VALIDATED" | "CONNECTION_TESTED" | "PENDING_APPROVAL" | "ACTIVE" | "SUPERSEDED" | "REJECTED" | "ROLLED_BACK";
export const ConfigVersionStatusValues = ["DRAFT", "VALIDATED", "CONNECTION_TESTED", "PENDING_APPROVAL", "ACTIVE", "SUPERSEDED", "REJECTED", "ROLLED_BACK"] as const;

export type OutboxStatus = "PENDING" | "PUBLISHING" | "PUBLISHED" | "RETRY_WAIT" | "DEAD_LETTER";
export const OutboxStatusValues = ["PENDING", "PUBLISHING", "PUBLISHED", "RETRY_WAIT", "DEAD_LETTER"] as const;

export type AccountingDirection = "DEBIT" | "CREDIT";
export const AccountingDirectionValues = ["DEBIT", "CREDIT"] as const;

