-- Generated from database/schema_dictionary.csv. Do not hand edit.
SET search_path TO hhy, public;


-- 商品 / 商品 / R16
CREATE TABLE hhy.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  name varchar(255),
  status varchar(64) NOT NULL,
  display_order integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.products IS '商品';


-- 商品 / SKU / R16
CREATE TABLE hhy.product_skus (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  code varchar(64) NOT NULL,
  price_cent bigint,
  duration integer,
  attributes_json jsonb,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.product_skus IS 'SKU';


-- 商品 / SKU分佣 / R16
CREATE TABLE hhy.sku_commission_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id bigint NOT NULL,
  level1_bps integer,
  level2_bps integer,
  enabled boolean DEFAULT false NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.sku_commission_policies IS 'SKU分佣';


-- 商品 / 优惠券定义 / R16
CREATE TABLE hhy.coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  discount_type integer,
  value bigint,
  scope varchar(64),
  validity varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.coupons IS '优惠券定义';


-- 商品 / 用户优惠券 / R16
CREATE TABLE hhy.user_coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  coupon_id bigint,
  status varchar(64) NOT NULL,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_coupons IS '用户优惠券';


-- 订单 / 订单主表 / R16
CREATE TABLE hhy.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no varchar(255) NOT NULL,
  user_id bigint NOT NULL,
  biz_type varchar(255),
  biz_id bigint,
  amount_cent bigint,
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.orders IS '订单主表';


-- 订单 / 订单项 / R16
CREATE TABLE hhy.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  sku_id bigint,
  quantity integer,
  unit_price bigint,
  snapshot_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.order_items IS '订单项';


-- 订单 / 报价快照 / R16
CREATE TABLE hhy.order_price_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  original bigint NOT NULL,
  discount bigint,
  service_fee bigint,
  payable bigint,
  rule_versions varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.order_price_snapshots IS '报价快照';


-- 支付 / 支付交易 / R17
CREATE TABLE hhy.payment_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  gateway varchar(255) NOT NULL,
  channel varchar(64),
  provider_trade_no varchar(128),
  amount bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payment_transactions IS '支付交易';


-- 支付 / 支付回调 / R17
CREATE TABLE hhy.payment_callbacks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway varchar(255) NOT NULL,
  provider_trade_no varchar(128),
  payload_cipher varchar(255),
  signature_valid boolean,
  processed boolean,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payment_callbacks IS '支付回调';


-- 支付 / 异常账务 / R17
CREATE TABLE hhy.payment_exception_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  type varchar(64),
  status varchar(64) NOT NULL,
  resolution varchar(255),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payment_exception_orders IS '异常账务';


-- 支付 / 支付对账 / R17
CREATE TABLE hhy.payment_reconciliation_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recon_date date NOT NULL,
  gateway varchar(255),
  result jsonb,
  diff_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payment_reconciliation_records IS '支付对账';


-- 会员 / 会员计划 / R18
CREATE TABLE hhy.membership_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  name varchar(255),
  public_badge varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_plans IS '会员计划';


-- 会员 / 月季年SKU / R18
CREATE TABLE hhy.membership_skus (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  term_type varchar(255),
  term_seconds varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_skus IS '月季年SKU';


-- 会员 / 权益定义 / R18
CREATE TABLE hhy.membership_benefits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  value_type bigint NOT NULL,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_benefits IS '权益定义';


-- 会员 / SKU权益 / R18
CREATE TABLE hhy.membership_sku_benefits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_sku_id bigint NOT NULL,
  benefit_id bigint NOT NULL,
  value_json jsonb,
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_sku_benefits IS 'SKU权益';


-- 会员 / 用户当前会员 / R18
CREATE TABLE hhy.user_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  plan_id bigint NOT NULL,
  status varchar(64) NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_memberships IS '用户当前会员';


-- 会员 / 付费/赠送分段 / R18
CREATE TABLE hhy.membership_entitlement_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  source_order_id bigint,
  type varchar(64),
  paid_amount bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  consumed bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_entitlement_segments IS '付费/赠送分段';


-- 会员 / 购买权益快照 / R18
CREATE TABLE hhy.membership_benefit_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  benefits_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  reward_matrix_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_benefit_snapshots IS '购买权益快照';


-- 会员 / 升级报价 / R18
CREATE TABLE hhy.membership_upgrade_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  target_sku_id bigint,
  remaining_value bigint,
  payable bigint,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_upgrade_quotes IS '升级报价';


-- 会员 / 价值转换 / R18
CREATE TABLE hhy.membership_value_conversions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upgrade_order_id bigint NOT NULL,
  source_segment_id bigint,
  converted_value bigint,
  extra_seconds varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.membership_value_conversions IS '价值转换';


-- 道具 / 道具定义 / R19
CREATE TABLE hhy.prop_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  name varchar(255),
  duration_seconds varchar(255),
  execution_type varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.prop_products IS '道具定义';


-- 道具 / 道具SKU / R19
CREATE TABLE hhy.prop_skus (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prop_id bigint NOT NULL,
  product_sku_id bigint,
  scope_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.prop_skus IS '道具SKU';


-- 道具 / 用户道具 / R19
CREATE TABLE hhy.user_props (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  prop_sku_id bigint,
  status varchar(64) NOT NULL,
  acquired_order_id bigint,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_props IS '用户道具';


-- 道具 / 持续曝光权益 / R19
CREATE TABLE hhy.content_exposure_entitlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  type varchar(64),
  starts_at timestamptz,
  ends_at timestamptz,
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_exposure_entitlements IS '持续曝光权益';


-- 道具 / 刷新记录 / R19
CREATE TABLE hhy.content_refresh_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  user_prop_id bigint,
  layers varchar(255),
  executed_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_refresh_records IS '刷新记录';


-- 道具 / 头条资源位 / R19
CREATE TABLE hhy.headline_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_code varchar(255) NOT NULL,
  slot_code varchar(255),
  capacity varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.headline_slots IS '头条资源位';


-- 道具 / 头条排期 / R19
CREATE TABLE hhy.headline_slot_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_id bigint NOT NULL,
  content_id bigint,
  entitlement_id bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.headline_slot_bookings IS '头条排期';


-- 道具 / 变色主题 / R19
CREATE TABLE hhy.color_themes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  token_json jsonb,
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.color_themes IS '变色主题';


-- 道具 / 道具执行 / R19
CREATE TABLE hhy.prop_execution_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_prop_id bigint NOT NULL,
  content_id bigint,
  result jsonb,
  error text,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.prop_execution_logs IS '道具执行';


-- 红包 / 活动主表 / R20-R23
CREATE TABLE hhy.red_packet_campaigns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  owner_id bigint,
  current_amount bigint,
  total_count integer DEFAULT 0 NOT NULL,
  status varchar(64) NOT NULL,
  required_seconds integer,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_campaigns IS '活动主表';


-- 红包 / 金额/规则版本 / R20-R23
CREATE TABLE hhy.red_packet_campaign_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  version_no varchar(255),
  amount bigint,
  remaining_at_effective varchar(255),
  rule_snapshot varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_campaign_versions IS '金额/规则版本';


-- 红包 / 创建/加价报价 / R20-R23
CREATE TABLE hhy.red_packet_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  quote_type varchar(255),
  principal bigint,
  service_fee bigint,
  payable bigint,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_quotes IS '创建/加价报价';


-- 红包 / 红包订单关联 / R20-R23
CREATE TABLE hhy.red_packet_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  order_id bigint,
  quote_id bigint,
  type varchar(64),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_orders IS '红包订单关联';


-- 红包 / 库存 / R20-R23
CREATE TABLE hhy.red_packet_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  total integer DEFAULT 0 NOT NULL,
  claimed integer DEFAULT 0 NOT NULL,
  reserved integer DEFAULT 0 NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_stock IS '库存';


-- 红包 / 浏览会话 / R20-R23
CREATE TABLE hhy.red_packet_view_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  user_id bigint NOT NULL,
  reservation_id bigint,
  required boolean,
  valid_seconds integer,
  status varchar(64) NOT NULL,
  expires_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_view_sessions IS '浏览会话';


-- 红包 / 心跳摘要/事件 / R20-R23
CREATE TABLE hhy.red_packet_heartbeats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL,
  server_time timestamptz,
  foreground boolean,
  visible boolean,
  delta bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_heartbeats IS '心跳摘要/事件';


-- 红包 / 名额锁定 / R20-R23
CREATE TABLE hhy.red_packet_reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  user_id bigint,
  session_id bigint,
  amount_version bigint,
  expires_at timestamptz,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_reservations IS '名额锁定';


-- 红包 / 领取 / R20-R23
CREATE TABLE hhy.red_packet_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  user_id bigint NOT NULL,
  amount bigint,
  amount_version bigint,
  status varchar(64) NOT NULL,
  reward_ledger_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_claims IS '领取';


-- 红包 / 任务证据 / R20-R23
CREATE TABLE hhy.red_packet_task_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id bigint NOT NULL,
  session_id bigint,
  evidence_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_task_evidence IS '任务证据';


-- 红包 / 红包资金账 / R20-R23
CREATE TABLE hhy.red_packet_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  entry_type varchar(255),
  amount bigint,
  balance_after bigint,
  biz_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_ledger IS '红包资金账';


-- 红包 / 活动统计 / R20-R23
CREATE TABLE hhy.red_packet_campaign_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint NOT NULL,
  metrics_json jsonb,
  updated_at timestamptz DEFAULT now() NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.red_packet_campaign_stats IS '活动统计';
