SET search_path TO hhy, public;

CREATE TABLE hhy.user_restrictions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES hhy.users(id) ON DELETE RESTRICT,
  restriction_type varchar(128) NOT NULL,
  reason text NOT NULL,
  expires_at timestamptz,
  status varchar(64) NOT NULL DEFAULT 'ACTIVE',
  created_by bigint NOT NULL REFERENCES hhy.admin_users(id) ON DELETE RESTRICT,
  removed_by bigint REFERENCES hhy.admin_users(id) ON DELETE RESTRICT,
  removed_at timestamptz,
  version bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_user_restrictions_type CHECK (restriction_type ~ '^[A-Za-z0-9_-]{1,128}$'),
  CONSTRAINT ck_user_restrictions_status CHECK (status IN ('ACTIVE','REMOVED','EXPIRED')),
  CONSTRAINT ck_user_restrictions_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
  CONSTRAINT ck_user_restrictions_removal CHECK (
    (status='ACTIVE' AND removed_at IS NULL AND removed_by IS NULL)
    OR (status<>'ACTIVE' AND removed_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_user_restrictions_active_type
  ON hhy.user_restrictions(user_id, restriction_type) WHERE status='ACTIVE';
CREATE INDEX ix_user_restrictions_user_status
  ON hhy.user_restrictions(user_id, status, expires_at);
CREATE INDEX ix_user_restrictions_expiry
  ON hhy.user_restrictions(expires_at) WHERE status='ACTIVE' AND expires_at IS NOT NULL;
CREATE TRIGGER trg_user_restrictions_updated_at BEFORE UPDATE ON hhy.user_restrictions
  FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

INSERT INTO hhy.admin_permissions(code,resource,action)
VALUES ('user.restrict','user','restrict'),('user.freeze','user','freeze'),('user.security','user','security')
ON CONFLICT(code) DO NOTHING;

INSERT INTO hhy.admin_role_permissions(role_id,permission_id)
SELECT role.id,permission.id FROM hhy.admin_roles role
CROSS JOIN hhy.admin_permissions permission
WHERE role.code='SUPER_ADMIN' AND role.status='ACTIVE'
  AND permission.code IN ('user.restrict','user.freeze','user.security')
ON CONFLICT(role_id,permission_id) DO NOTHING;

DO $$
BEGIN
  IF (SELECT count(*) FROM hhy.admin_permissions
      WHERE code IN ('user.restrict','user.freeze','user.security')) <> 3 THEN
    RAISE EXCEPTION 'R02_USER_CONTROL_PERMISSIONS_INCOMPLETE';
  END IF;
  IF (SELECT count(*) FROM hhy.admin_role_permissions role_permission
      JOIN hhy.admin_roles role ON role.id=role_permission.role_id
      JOIN hhy.admin_permissions permission ON permission.id=role_permission.permission_id
      WHERE role.code='SUPER_ADMIN'
        AND permission.code IN ('user.restrict','user.freeze','user.security')) <> 3 THEN
    RAISE EXCEPTION 'R02_SUPER_ADMIN_USER_CONTROL_GRANT_INCOMPLETE';
  END IF;
END $$;

