-- R14 user-scoped WebSocket delivery, acknowledgement, and resume facts.
SET search_path TO hhy, public;

CREATE TABLE hhy.websocket_user_sequences (
  user_id bigint PRIMARY KEY REFERENCES hhy.users(id) ON DELETE RESTRICT,
  high_watermark bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT ck_r14_ws_sequence_nonnegative CHECK (high_watermark >= 0)
);
COMMENT ON TABLE hhy.websocket_user_sequences IS 'R14 WebSocket user-scoped contiguous server sequence';

CREATE TABLE hhy.websocket_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id uuid NOT NULL,
  user_id bigint NOT NULL REFERENCES hhy.users(id) ON DELETE RESTRICT,
  server_sequence bigint NOT NULL,
  event_type varchar(64) NOT NULL,
  conversation_id bigint REFERENCES hhy.conversations(id) ON DELETE RESTRICT,
  affected_scope varchar(32) NOT NULL,
  envelope jsonb NOT NULL,
  ack_required boolean DEFAULT false NOT NULL,
  acked_at timestamptz,
  delivery_attempts smallint DEFAULT 0 NOT NULL,
  first_delivered_at timestamptz,
  last_delivered_at timestamptz,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT uq_r14_ws_delivery_event UNIQUE (event_id),
  CONSTRAINT uq_r14_ws_delivery_sequence UNIQUE (user_id, server_sequence),
  CONSTRAINT ck_r14_ws_delivery_sequence_positive CHECK (server_sequence > 0),
  CONSTRAINT ck_r14_ws_delivery_event_type CHECK (btrim(event_type) <> ''),
  CONSTRAINT ck_r14_ws_delivery_scope CHECK (affected_scope IN ('CHAT', 'NOTIFICATIONS')),
  CONSTRAINT ck_r14_ws_delivery_envelope CHECK (jsonb_typeof(envelope) = 'object'),
  CONSTRAINT ck_r14_ws_delivery_attempts CHECK (delivery_attempts BETWEEN 0 AND 6),
  CONSTRAINT ck_r14_ws_delivery_ack CHECK (acked_at IS NULL OR ack_required),
  CONSTRAINT ck_r14_ws_delivery_times CHECK (
    expires_at >= created_at + interval '72 hours'
    AND (first_delivered_at IS NULL OR first_delivered_at >= created_at)
    AND (last_delivered_at IS NULL OR first_delivered_at IS NOT NULL)
    AND (last_delivered_at IS NULL OR last_delivered_at >= first_delivered_at)
    AND (acked_at IS NULL OR acked_at >= created_at)
  )
);
COMMENT ON TABLE hhy.websocket_deliveries IS 'R14 persisted S2C events with ACK and redelivery state';

CREATE TABLE hhy.websocket_gap_watermarks (
  user_id bigint PRIMARY KEY REFERENCES hhy.users(id) ON DELETE RESTRICT,
  expired_through_sequence bigint DEFAULT 0 NOT NULL,
  affected_scopes varchar(32)[] DEFAULT ARRAY[]::varchar(32)[] NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT ck_r14_ws_gap_sequence_nonnegative CHECK (expired_through_sequence >= 0),
  CONSTRAINT ck_r14_ws_gap_scopes CHECK (
    affected_scopes <@ ARRAY['CHAT', 'NOTIFICATIONS']::varchar(32)[]
    AND cardinality(affected_scopes) <= 2
  )
);
COMMENT ON TABLE hhy.websocket_gap_watermarks IS 'R14 expired delivery watermark and authoritative REST gap scopes';

CREATE INDEX ix_r14_ws_delivery_resume
  ON hhy.websocket_deliveries(user_id, server_sequence);
CREATE INDEX ix_r14_ws_delivery_retry
  ON hhy.websocket_deliveries(last_delivered_at, created_at)
  WHERE ack_required AND acked_at IS NULL AND delivery_attempts < 6;
CREATE INDEX ix_r14_ws_delivery_expiry
  ON hhy.websocket_deliveries(user_id, expires_at);

CREATE OR REPLACE FUNCTION hhy.guard_r14_ws_sequence()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.user_id <> OLD.user_id OR NEW.high_watermark < OLD.high_watermark THEN
    RAISE EXCEPTION 'R14_WS_SEQUENCE_REGRESSION' USING ERRCODE='23514';
  END IF;
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_r14_ws_sequence_guard
BEFORE UPDATE ON hhy.websocket_user_sequences
FOR EACH ROW EXECUTE FUNCTION hhy.guard_r14_ws_sequence();

CREATE OR REPLACE FUNCTION hhy.guard_r14_ws_delivery()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(NEW.event_id, NEW.user_id, NEW.server_sequence, NEW.event_type,
         NEW.conversation_id, NEW.affected_scope, NEW.envelope, NEW.ack_required,
         NEW.expires_at, NEW.created_at)
     IS DISTINCT FROM
     ROW(OLD.event_id, OLD.user_id, OLD.server_sequence, OLD.event_type,
         OLD.conversation_id, OLD.affected_scope, OLD.envelope, OLD.ack_required,
         OLD.expires_at, OLD.created_at) THEN
    RAISE EXCEPTION 'R14_WS_DELIVERY_IMMUTABLE_FACT' USING ERRCODE='23514';
  END IF;
  IF NEW.delivery_attempts < OLD.delivery_attempts
     OR (OLD.acked_at IS NOT NULL AND NEW.acked_at IS DISTINCT FROM OLD.acked_at)
     OR (OLD.first_delivered_at IS NOT NULL AND NEW.first_delivered_at IS DISTINCT FROM OLD.first_delivered_at)
     OR (OLD.last_delivered_at IS NOT NULL AND NEW.last_delivered_at < OLD.last_delivered_at) THEN
    RAISE EXCEPTION 'R14_WS_DELIVERY_STATE_REGRESSION' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_r14_ws_delivery_guard
BEFORE UPDATE ON hhy.websocket_deliveries
FOR EACH ROW EXECUTE FUNCTION hhy.guard_r14_ws_delivery();

CREATE OR REPLACE FUNCTION hhy.guard_r14_ws_gap_watermark()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.user_id <> OLD.user_id
     OR NEW.expired_through_sequence < OLD.expired_through_sequence
     OR NOT OLD.affected_scopes <@ NEW.affected_scopes THEN
    RAISE EXCEPTION 'R14_WS_GAP_WATERMARK_REGRESSION' USING ERRCODE='23514';
  END IF;
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_r14_ws_gap_watermark_guard
BEFORE UPDATE ON hhy.websocket_gap_watermarks
FOR EACH ROW EXECUTE FUNCTION hhy.guard_r14_ws_gap_watermark();
