-- Generated from database/schema_dictionary.csv. Do not hand edit.
SET search_path TO hhy, public;


-- 账号 / 用户主账号 / R02
CREATE TABLE hhy.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone varchar(32) NOT NULL,
  status varchar(64) NOT NULL,
  invite_code varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.users IS '用户主账号';


-- 账号 / 登录凭证 / R02
CREATE TABLE hhy.user_credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  password_hash varchar(128) NOT NULL,
  algorithm varchar(64),
  password_changed_at timestamptz,
  failed_count integer,
  locked_until timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_credentials IS '登录凭证';


-- 账号 / 安全验证挑战 / R02
CREATE TABLE hhy.auth_security_challenges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  answer_hash varchar(128),
  expires_at timestamptz,
  used_at timestamptz,
  ip varchar(64),
  device_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.auth_security_challenges IS '安全验证挑战';


-- 账号 / 重置密码会话 / R02
CREATE TABLE hhy.password_reset_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone varchar(32) NOT NULL,
  sms_verification_id bigint,
  expires_at timestamptz,
  used_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.password_reset_sessions IS '重置密码会话';


-- 账号 / 注册记录 / R02
CREATE TABLE hhy.registration_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  channel varchar(64),
  phone varchar(32),
  invite_code varchar(255),
  inviter_id bigint,
  rule_version varchar(255),
  ip varchar(64),
  device_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.registration_records IS '注册记录';


-- 账号 / 公开资料 / R02
CREATE TABLE hhy.user_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  nickname varchar(255) NOT NULL,
  avatar varchar(255),
  bio varchar(255),
  region varchar(255),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_profiles IS '公开资料';


-- 账号 / 登录会话 / R02
CREATE TABLE hhy.user_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  access_jti varchar(128) NOT NULL,
  refresh_hash varchar(128),
  device_id bigint,
  expires_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_sessions IS '登录会话';


-- 账号 / 设备 / R02
CREATE TABLE hhy.user_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  device_fingerprint varchar(128),
  model varchar(255),
  last_seen timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_devices IS '设备';


-- 账号 / 验证码 / R02
CREATE TABLE hhy.sms_verification_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone varchar(32) NOT NULL,
  scene varchar(64),
  code_hash varchar(128),
  expires_at timestamptz,
  attempts integer,
  provider_message_id varchar(128),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.sms_verification_codes IS '验证码';


-- 账号 / 阿里云短信发送记录 / R02
CREATE TABLE hhy.sms_send_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone varchar(32) NOT NULL,
  scene varchar(64),
  template_code varchar(255),
  provider_message_id varchar(128),
  result jsonb,
  ip varchar(64),
  device_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.sms_send_logs IS '阿里云短信发送记录';


-- 账号 / 登录日志 / R02
CREATE TABLE hhy.login_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  phone varchar(32),
  ip varchar(64),
  device_id bigint,
  result jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.login_logs IS '登录日志';


-- 账号 / 用户设置 / R02
CREATE TABLE hhy.user_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  notification_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  privacy_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_settings IS '用户设置';


-- 账号 / 账号状态历史 / R02
CREATE TABLE hhy.user_status_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  from_status varchar(255),
  to_status varchar(255),
  reason text,
  operator varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_status_logs IS '账号状态历史';


-- 版本 / App版本 / P00/R29/R30
CREATE TABLE hhy.app_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_code integer NOT NULL,
  version_name varchar(255) NOT NULL,
  apk_media_id bigint,
  update_type varchar(255),
  min_version integer,
  sha256 varchar(128),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_versions IS 'App版本';


-- 后台 / 后台账号 / R01/R03/R30
CREATE TABLE hhy.admin_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(255) NOT NULL,
  password_hash varchar(128) NOT NULL,
  status varchar(64) NOT NULL,
  mfa_secret_ref varchar(255),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_users IS '后台账号';


-- 后台 / 角色 / R01/R03/R30
CREATE TABLE hhy.admin_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_roles IS '角色';


-- 后台 / 权限 / R01/R03/R30
CREATE TABLE hhy.admin_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  resource varchar(255) NOT NULL,
  action varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_permissions IS '权限';


-- 后台 / 用户角色 / R01/R03/R30
CREATE TABLE hhy.admin_user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL,
  role_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_user_roles IS '用户角色';


-- 后台 / 角色权限 / R01/R03/R30
CREATE TABLE hhy.admin_role_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id bigint NOT NULL,
  permission_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_role_permissions IS '角色权限';


-- 后台 / 操作审计 / R01/R03/R30
CREATE TABLE hhy.admin_operation_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL,
  action varchar(255),
  resource varchar(255),
  resource_id bigint,
  before_json jsonb,
  after_json jsonb,
  ip varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_operation_logs IS '操作审计';


-- 后台 / 双人复核 / R01/R03/R30
CREATE TABLE hhy.admin_approval_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  biz_id bigint,
  requester varchar(255),
  reviewer varchar(255),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.admin_approval_requests IS '双人复核';


-- 系统 / 当前配置 / P00/R29/R30
CREATE TABLE hhy.system_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(255) NOT NULL,
  value_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  scope varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.system_configs IS '当前配置';


-- 系统 / 配置历史 / P00/R29/R30
CREATE TABLE hhy.system_config_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(255) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  value_json jsonb,
  changed_by varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.system_config_versions IS '配置历史';


-- 系统 / 功能开关 / P00/R29/R30
CREATE TABLE hhy.feature_flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(255) NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  rollout_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.feature_flags IS '功能开关';


-- 系统 / 幂等记录 / P00/R29/R30
CREATE TABLE hhy.idempotency_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope varchar(64) NOT NULL,
  idem_key varchar(255) NOT NULL,
  request_hash varchar(128),
  response_ref varchar(255),
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.idempotency_records IS '幂等记录';


-- 配置中心 / 供应商配置定义 / R01/R03/R30
CREATE TABLE hhy.provider_config_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code varchar(64) NOT NULL,
  field_code varchar(64) NOT NULL,
  field_type varchar(255),
  secret boolean,
  required boolean,
  validation_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.provider_config_definitions IS '供应商配置定义';


-- 配置中心 / 供应商配置版本 / R01/R03/R30
CREATE TABLE hhy.provider_config_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code varchar(64) NOT NULL,
  version_no varchar(255) NOT NULL,
  encrypted_values bigint,
  status varchar(64) NOT NULL,
  created_by varchar(255),
  activated_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.provider_config_versions IS '供应商配置版本';


-- 配置中心 / 供应商连接测试 / R01/R03/R30
CREATE TABLE hhy.provider_connection_tests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code varchar(64) NOT NULL,
  config_version_id bigint,
  test_type varchar(255),
  status varchar(64) NOT NULL,
  masked_result varchar(255),
  requested_by varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.provider_connection_tests IS '供应商连接测试';


-- 配置中心 / 证书与私钥元数据 / R01/R03/R30
CREATE TABLE hhy.provider_certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code varchar(64) NOT NULL,
  cert_type varchar(255),
  object_key text,
  fingerprint varchar(128),
  encrypted_password_ref varchar(255),
  valid_from timestamptz,
  valid_to timestamptz,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.provider_certificates IS '证书与私钥元数据';


-- 配置中心 / 证书访问审计 / R01/R03/R30
CREATE TABLE hhy.provider_certificate_access_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_id bigint NOT NULL,
  admin_id bigint,
  operation varchar(64),
  reason text,
  ip varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.provider_certificate_access_logs IS '证书访问审计';


-- 配置中心 / 域名配置 / R01/R03/R30
CREATE TABLE hhy.domain_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  environment varchar(64) NOT NULL,
  host varchar(255),
  purpose varchar(255),
  status varchar(64) NOT NULL,
  verified_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.domain_configs IS '域名配置';


-- 配置中心 / DNS操作清单 / R01/R03/R30
CREATE TABLE hhy.dns_action_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_config_id bigint NOT NULL,
  record_type varchar(255),
  name varchar(255),
  value bigint,
  status varchar(64) NOT NULL,
  user_action_required boolean,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.dns_action_items IS 'DNS操作清单';


-- 配置中心 / 存储Scope绑定 / R01/R03/R30
CREATE TABLE hhy.storage_scope_bindings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_code varchar(255) NOT NULL,
  provider_code varchar(64) NOT NULL,
  config_version_id bigint,
  bucket varchar(255),
  public_domain varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.storage_scope_bindings IS '存储Scope绑定';


-- 配置中心 / 跨存储迁移任务 / R01/R03/R30
CREATE TABLE hhy.storage_migration_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_binding_id bigint NOT NULL,
  target_binding_id bigint,
  scope_code varchar(255),
  cursor varchar(255),
  total integer DEFAULT 0 NOT NULL,
  success integer,
  failed integer,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.storage_migration_jobs IS '跨存储迁移任务';


-- 平台事件 / 事务事件发件箱 / P00
CREATE TABLE hhy.outbox_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  aggregate_id varchar(128) NOT NULL,
  aggregate_type varchar(64) NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  available_at timestamptz DEFAULT now() NOT NULL,
  event_id varchar(64) NOT NULL,
  event_type varchar(128) NOT NULL,
  event_version integer DEFAULT 1 NOT NULL,
  headers jsonb DEFAULT '{}'::jsonb NOT NULL,
  last_error text,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  published_at timestamptz,
  status varchar(64) DEFAULT 'PENDING' NOT NULL
);
COMMENT ON TABLE hhy.outbox_events IS '事务事件发件箱';


-- 平台事件 / 消费者幂等收件箱 / P00
CREATE TABLE hhy.inbox_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  consumer varchar(128) NOT NULL,
  message_id varchar(64) NOT NULL,
  payload_hash varchar(64) NOT NULL,
  processed_at timestamptz DEFAULT now() NOT NULL,
  result jsonb
);
COMMENT ON TABLE hhy.inbox_messages IS '消费者幂等收件箱';


-- 账务 / 统一会计账户 / P00
CREATE TABLE hhy.ledger_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  account_no varchar(64) NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(8) DEFAULT 'CNY' NOT NULL,
  owner_id varchar(128) NOT NULL,
  owner_type varchar(64) NOT NULL,
  status varchar(64) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE hhy.ledger_accounts IS '统一会计账户';


-- 账务 / 不可变会计交易 / P00
CREATE TABLE hhy.accounting_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  biz_id varchar(128) NOT NULL,
  biz_type varchar(64) NOT NULL,
  description varchar(255),
  idempotency_key varchar(128) NOT NULL,
  occurred_at timestamptz DEFAULT now() NOT NULL,
  reversal_of_id bigint,
  status varchar(64) DEFAULT 'POSTED' NOT NULL,
  transaction_no varchar(64) NOT NULL
);
COMMENT ON TABLE hhy.accounting_transactions IS '不可变会计交易';


-- 账务 / 复式会计分录 / P00
CREATE TABLE hhy.accounting_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  account_id bigint NOT NULL,
  amount_cent bigint NOT NULL,
  currency varchar(8) DEFAULT 'CNY' NOT NULL,
  direction varchar(64) NOT NULL,
  sequence integer NOT NULL,
  transaction_id bigint NOT NULL
);
COMMENT ON TABLE hhy.accounting_entries IS '复式会计分录';


-- 账务 / 账户余额投影 / P00
CREATE TABLE hhy.balance_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  account_id bigint NOT NULL,
  as_of_entry_id bigint DEFAULT 0 NOT NULL,
  available_cent bigint DEFAULT 0 NOT NULL,
  frozen_cent bigint DEFAULT 0 NOT NULL
);
COMMENT ON TABLE hhy.balance_snapshots IS '账户余额投影';


-- 账务 / 统一对账批次 / P00
CREATE TABLE hhy.reconciliation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  finished_at timestamptz,
  period_end timestamptz NOT NULL,
  period_start timestamptz NOT NULL,
  run_no varchar(64) NOT NULL,
  scene varchar(64) NOT NULL,
  started_at timestamptz,
  status varchar(64) DEFAULT 'CREATED' NOT NULL
);
COMMENT ON TABLE hhy.reconciliation_runs IS '统一对账批次';


-- 账务 / 对账差异 / P00
CREATE TABLE hhy.reconciliation_differences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  actual_cent bigint DEFAULT 0 NOT NULL,
  expected_cent bigint DEFAULT 0 NOT NULL,
  resolution text,
  run_id bigint NOT NULL,
  source_id varchar(128) NOT NULL,
  source_type varchar(64) NOT NULL,
  status varchar(64) DEFAULT 'OPEN' NOT NULL
);
COMMENT ON TABLE hhy.reconciliation_differences IS '对账差异';
