-- Generated from database/schema_dictionary.csv. Do not hand edit.
SET search_path TO hhy, public;


-- 实名 / 当前实名资料 / R05
CREATE TABLE hhy.identity_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name_cipher varchar(255) NOT NULL,
  id_no_cipher varchar(255),
  id_hash varchar(128),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.identity_profiles IS '当前实名资料';


-- 实名 / 实名尝试 / R05
CREATE TABLE hhy.identity_verification_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  state varchar(255) NOT NULL,
  status varchar(64) NOT NULL,
  provider varchar(255),
  expires_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.identity_verification_sessions IS '实名尝试';


-- 实名 / 第三方请求记录 / R05
CREATE TABLE hhy.identity_provider_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL,
  request_type varchar(255),
  provider_order_no varchar(128),
  response_cipher varchar(255),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.identity_provider_requests IS '第三方请求记录';


-- 实名 / 实名媒体 / R05
CREATE TABLE hhy.identity_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL,
  media_object_id bigint,
  media_type varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.identity_media IS '实名媒体';


-- 实名 / 人工复核 / R05
CREATE TABLE hhy.identity_review_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL,
  decision varchar(64),
  reason text,
  admin_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.identity_review_records IS '人工复核';


-- 实名 / 敏感查看日志 / R05
CREATE TABLE hhy.sensitive_data_access_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL,
  user_id bigint,
  resource varchar(255),
  reason text,
  ip varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.sensitive_data_access_logs IS '敏感查看日志';


-- 媒体 / 对象元数据 / R04
CREATE TABLE hhy.media_objects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL,
  bucket varchar(255) NOT NULL,
  object_key text,
  mime varchar(255),
  size bigint,
  sha256 varchar(128),
  visibility varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.media_objects IS '对象元数据';


-- 媒体 / 上传会话 / R04
CREATE TABLE hhy.upload_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  scene varchar(64),
  status varchar(64) NOT NULL,
  expires_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.upload_sessions IS '上传会话';


-- 媒体 / 临时访问令牌 / R04
CREATE TABLE hhy.media_access_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_id bigint NOT NULL,
  subject varchar(255),
  expires_at timestamptz,
  used_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.media_access_tokens IS '临时访问令牌';


-- 内容 / 内容主表 / R06-R13
CREATE TABLE hhy.content_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL,
  type varchar(64),
  title varchar(255),
  summary text,
  status varchar(64) NOT NULL,
  review_status varchar(64),
  refresh_times integer,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_posts IS '内容主表';


-- 内容 / 项目扩展 / R06-R13
CREATE TABLE hhy.project_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  cooperation varchar(255) NOT NULL,
  conditions varchar(255),
  region varchar(255),
  website varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.project_details IS '项目扩展';


-- 内容 / App扩展 / R06-R13
CREATE TABLE hhy.app_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  app_name varchar(255) NOT NULL,
  platform varchar(255),
  version_text varchar(255),
  download_url text,
  website varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_details IS 'App扩展';


-- 内容 / 群扩展 / R06-R13
CREATE TABLE hhy.group_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  platform varchar(255) NOT NULL,
  size_range varchar(255),
  join_requirement varchar(255),
  qr_media_id bigint,
  group_link varchar(255),
  group_no varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.group_details IS '群扩展';


-- 内容 / 团队长扩展 / R06-R13
CREATE TABLE hhy.team_leader_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  team_name varchar(255) NOT NULL,
  size_range varchar(255),
  skills varchar(255),
  cooperation_types varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.team_leader_details IS '团队长扩展';


-- 内容 / 内容媒体 / R06-R13
CREATE TABLE hhy.content_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  media_id bigint NOT NULL,
  media_type varchar(255),
  sort_order integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_media IS '内容媒体';


-- 内容 / 内容联系方式 / R06-R13
CREATE TABLE hhy.content_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  channel varchar(64),
  value_cipher bigint,
  display_mask varchar(255),
  sort_order integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_contacts IS '内容联系方式';


-- 内容 / 内容版本 / R06-R13
CREATE TABLE hhy.content_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  version_no varchar(255) NOT NULL,
  snapshot_json jsonb,
  created_by varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_versions IS '内容版本';


-- 内容 / 状态日志 / R06-R13
CREATE TABLE hhy.content_status_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  from_status varchar(255),
  to_status varchar(255),
  reason text,
  operator varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_status_logs IS '状态日志';


-- 内容 / 审核记录 / R06-R13
CREATE TABLE hhy.content_review_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  version_no varchar(255),
  decision varchar(64),
  reason text,
  admin_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_review_records IS '审核记录';


-- 内容 / 累计统计 / R06-R13
CREATE TABLE hhy.content_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  organic_views varchar(255) NOT NULL,
  redpacket_views varchar(255),
  task_views varchar(255),
  favorites varchar(255),
  chats varchar(255),
  contacts varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_stats IS '累计统计';


-- 内容 / 每日统计 / R06-R13
CREATE TABLE hhy.content_daily_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  stat_date date NOT NULL,
  metrics_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_daily_stats IS '每日统计';


-- 内容 / 收藏 / R06-R13
CREATE TABLE hhy.content_favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_favorites IS '收藏';


-- 内容 / 浏览事件 / R06-R13
CREATE TABLE hhy.content_view_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content_id bigint,
  traffic_type varchar(64),
  duration integer,
  source varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_view_logs IS '浏览事件';


-- 内容 / 联系方式访问 / R06-R13
CREATE TABLE hhy.content_contact_access_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content_id bigint,
  channel varchar(64),
  action varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_contact_access_logs IS '联系方式访问';


-- 内容 / 内容举报 / R06-R13
CREATE TABLE hhy.content_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id bigint NOT NULL,
  content_id bigint,
  type varchar(64),
  description text,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_reports IS '内容举报';


-- 内容 / 内容申诉 / R06-R13
CREATE TABLE hhy.content_appeals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id bigint NOT NULL,
  owner_id bigint,
  review_record_id bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.content_appeals IS '内容申诉';


-- 内容 / 关注发布者 / R06-R13
CREATE TABLE hhy.publisher_follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  publisher_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.publisher_follows IS '关注发布者';


-- 搜索 / 搜索历史 / R07
CREATE TABLE hhy.search_histories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  keyword varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.search_histories IS '搜索历史';


-- 搜索 / 热搜词 / R07
CREATE TABLE hhy.hot_search_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword varchar(255) NOT NULL,
  weight integer,
  enabled boolean DEFAULT false NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.hot_search_terms IS '热搜词';


-- 聊天 / 会话 / R14
CREATE TABLE hhy.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  last_message_id bigint,
  last_message_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.conversations IS '会话';


-- 聊天 / 会话成员 / R14
CREATE TABLE hhy.conversation_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL,
  user_id bigint NOT NULL,
  unread_count integer,
  last_read_message_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.conversation_members IS '会话成员';


-- 聊天 / 消息 / R14
CREATE TABLE hhy.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL,
  sender_id bigint NOT NULL,
  type varchar(64),
  body_json jsonb,
  status varchar(64) NOT NULL,
  client_msg_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.chat_messages IS '消息';


-- 聊天 / 消息附件 / R14
CREATE TABLE hhy.chat_message_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL,
  media_id bigint,
  sort_order integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.chat_message_attachments IS '消息附件';


-- 聊天 / 已读 / R14
CREATE TABLE hhy.chat_read_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL,
  user_id bigint NOT NULL,
  read_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.chat_read_receipts IS '已读';


-- 聊天 / 拉黑 / R14
CREATE TABLE hhy.user_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  blocked_user_id bigint NOT NULL,
  reason text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_blocks IS '拉黑';


-- 聊天 / 聊天举报 / R14
CREATE TABLE hhy.chat_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id bigint NOT NULL,
  target_user_id bigint,
  conversation_id bigint,
  message_ids jsonb,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.chat_reports IS '聊天举报';


-- 通知 / 站内通知 / R15
CREATE TABLE hhy.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  type varchar(64),
  title varchar(255),
  body text,
  biz_type varchar(255),
  biz_id bigint,
  read_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.notifications IS '站内通知';


-- 通知 / 通知模板 / R15
CREATE TABLE hhy.notification_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  channel varchar(64) NOT NULL,
  template varchar(255),
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.notification_templates IS '通知模板';


-- 通知 / 发送记录 / R15
CREATE TABLE hhy.notification_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id bigint NOT NULL,
  channel varchar(64),
  status varchar(64) NOT NULL,
  provider_msg_id varchar(128),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.notification_deliveries IS '发送记录';


-- 通知 / 推送令牌 / R15
CREATE TABLE hhy.push_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  device_id bigint NOT NULL,
  provider varchar(255),
  token varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.push_tokens IS '推送令牌';


-- 通知 / 公告 / R15
CREATE TABLE hhy.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  content text,
  status varchar(64) NOT NULL,
  published_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.announcements IS '公告';


-- 通知 / 公告已读 / R15
CREATE TABLE hhy.announcement_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id bigint NOT NULL,
  user_id bigint NOT NULL,
  read_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.announcement_reads IS '公告已读';


-- 客服 / 工单 / R15
CREATE TABLE hhy.support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no varchar(255) NOT NULL,
  user_id bigint NOT NULL,
  type varchar(64),
  biz_type varchar(255),
  biz_id bigint,
  status varchar(64) NOT NULL,
  assignee varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.support_tickets IS '工单';


-- 客服 / 工单消息 / R15
CREATE TABLE hhy.ticket_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL,
  sender_type varchar(255),
  sender_id bigint,
  body text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.ticket_messages IS '工单消息';


-- 客服 / 工单附件 / R15
CREATE TABLE hhy.ticket_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL,
  message_id bigint,
  media_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.ticket_attachments IS '工单附件';


-- 客服 / 工单状态 / R15
CREATE TABLE hhy.ticket_status_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL,
  from_status varchar(255),
  to_status varchar(255),
  operator varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.ticket_status_logs IS '工单状态';
