-- Generated from database/schema_dictionary.csv. Do not hand edit.
SET search_path TO hhy, public;


-- 奖励 / 奖励账户 / R24
CREATE TABLE hhy.reward_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  pending bigint DEFAULT 0 NOT NULL,
  available bigint DEFAULT 0 NOT NULL,
  frozen bigint DEFAULT 0 NOT NULL,
  withdrawing bigint DEFAULT 0 NOT NULL,
  withdrawn bigint DEFAULT 0 NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.reward_accounts IS '奖励账户';


-- 奖励 / 奖励流水 / R24
CREATE TABLE hhy.reward_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  source_type varchar(255),
  amount bigint,
  status varchar(64) NOT NULL,
  biz_id bigint,
  balance_after bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.reward_ledger IS '奖励流水';


-- 奖励 / 结算任务 / R24
CREATE TABLE hhy.reward_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ledger_id bigint NOT NULL,
  settle_at timestamptz,
  status varchar(64) NOT NULL,
  risk_result varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.reward_settlements IS '结算任务';


-- 奖励 / 冻结记录 / R24
CREATE TABLE hhy.reward_freezes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  ledger_id bigint,
  reason text,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.reward_freezes IS '冻结记录';


-- 提现 / 支付宝账户 / R24
CREATE TABLE hhy.payout_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_cipher integer NOT NULL,
  account_hash integer,
  real_name varchar(255),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payout_accounts IS '支付宝账户';


-- 提现 / 提现申请 / R24
CREATE TABLE hhy.withdrawal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdraw_no varchar(255) NOT NULL,
  user_id bigint NOT NULL,
  amount bigint,
  fee bigint,
  net_amount bigint,
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.withdrawal_requests IS '提现申请';


-- 提现 / 出款交易 / R24
CREATE TABLE hhy.payout_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_id bigint NOT NULL,
  gateway varchar(255) NOT NULL,
  provider_order_no varchar(128),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payout_transactions IS '出款交易';


-- 提现 / 出款回调 / R24
CREATE TABLE hhy.payout_callbacks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_order_no varchar(128) NOT NULL,
  payload_cipher varchar(255),
  processed boolean,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payout_callbacks IS '出款回调';


-- 提现 / 出款对账 / R24
CREATE TABLE hhy.payout_reconciliation_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recon_date date NOT NULL,
  result jsonb,
  diff_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.payout_reconciliation_records IS '出款对账';


-- 推广 / 邀请码 / R25
CREATE TABLE hhy.invite_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  code varchar(64) NOT NULL,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.invite_codes IS '邀请码';


-- 推广 / 邀请关系 / R25
CREATE TABLE hhy.referral_relations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_id bigint NOT NULL,
  invitee_id bigint NOT NULL,
  level1_parent_id bigint,
  bound_at timestamptz,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_relations IS '邀请关系';


-- 推广 / 绑定历史 / R25
CREATE TABLE hhy.referral_binding_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invitee_id bigint NOT NULL,
  old_inviter varchar(255),
  new_inviter varchar(255),
  reason text,
  admin_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_binding_logs IS '绑定历史';


-- 推广 / 佣金规则版本 / R25
CREATE TABLE hhy.commission_policy_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  starts_at timestamptz,
  config_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.commission_policy_versions IS '佣金规则版本';


-- 推广 / 佣金记录 / R25
CREATE TABLE hhy.commission_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  beneficiary_id bigint NOT NULL,
  source_user_id bigint,
  level integer,
  base bigint,
  rate varchar(255),
  amount bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.commission_records IS '佣金记录';


-- 推广 / 佣金结算 / R25
CREATE TABLE hhy.commission_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commission_id bigint NOT NULL,
  settle_at timestamptz,
  risk_result varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.commission_settlements IS '佣金结算';


-- 推广 / 推广素材 / R25
CREATE TABLE hhy.referral_materials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  title varchar(255),
  content text,
  media_id bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_materials IS '推广素材';


-- 推广 / 推广违规 / R25
CREATE TABLE hhy.referral_violation_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  type varchar(64),
  evidence varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_violation_records IS '推广违规';


-- 推广活跃 / 活跃规则版本 / R26
CREATE TABLE hhy.referral_activity_rule_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  starts_at timestamptz,
  daily_cap varchar(255),
  config_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_activity_rule_versions IS '活跃规则版本';


-- 推广活跃 / 行为分值 / R26
CREATE TABLE hhy.referral_activity_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL,
  event_type varchar(255) NOT NULL,
  score integer,
  frequency varchar(255),
  conditions_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_activity_rules IS '行为分值';


-- 推广活跃 / 每名直推进度 / R26
CREATE TABLE hhy.referral_activity_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_id bigint NOT NULL,
  invitee_id bigint NOT NULL,
  current_score integer,
  highest_milestone varchar(255),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_activity_progress IS '每名直推进度';


-- 推广活跃 / 活跃事件 / R26
CREATE TABLE hhy.referral_activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_id bigint NOT NULL,
  invitee_id bigint NOT NULL,
  event_type varchar(255),
  delta bigint,
  before varchar(255),
  after varchar(255),
  biz_id bigint,
  idem_key varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_activity_events IS '活跃事件';


-- 推广活跃 / 档位 / R26
CREATE TABLE hhy.referral_milestones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL,
  score integer NOT NULL,
  sequence integer,
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_milestones IS '档位';


-- 推广活跃 / 会员奖励矩阵 / R26
CREATE TABLE hhy.referral_reward_matrix (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milestone_id bigint NOT NULL,
  member_term varchar(255),
  reward_amount bigint,
  enabled boolean DEFAULT false NOT NULL,
  settle_delay varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_reward_matrix IS '会员奖励矩阵';


-- 推广活跃 / 档位奖励 / R26
CREATE TABLE hhy.referral_milestone_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_id bigint NOT NULL,
  inviter_id bigint NOT NULL,
  invitee_id bigint,
  milestone varchar(255),
  member_snapshot varchar(255),
  amount bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.referral_milestone_rewards IS '档位奖励';


-- 任务 / 任务定义 / R27
CREATE TABLE hhy.task_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  type varchar(64) NOT NULL,
  cycle varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.task_definitions IS '任务定义';


-- 任务 / 任务规则版本 / R27
CREATE TABLE hhy.task_rule_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  conditions_json jsonb,
  rewards_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.task_rule_versions IS '任务规则版本';


-- 任务 / 任务进度 / R27
CREATE TABLE hhy.user_task_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  task_id bigint NOT NULL,
  cycle_key varchar(255),
  progress varchar(255),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_task_progress IS '任务进度';


-- 任务 / 任务事件 / R27
CREATE TABLE hhy.task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  event_type varchar(255) NOT NULL,
  biz_id bigint,
  idem_key varchar(255),
  payload jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.task_events IS '任务事件';


-- 任务 / 个人任务积分账户 / R27
CREATE TABLE hhy.user_point_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  balance bigint NOT NULL,
  accumulated varchar(255),
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_point_accounts IS '个人任务积分账户';


-- 任务 / 个人积分流水 / R27
CREATE TABLE hhy.user_point_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  delta bigint,
  source varchar(255),
  biz_id bigint,
  balance_after bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_point_ledger IS '个人积分流水';


-- 任务 / 个人里程碑奖励 / R27
CREATE TABLE hhy.task_milestone_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  milestone varchar(255) NOT NULL,
  reward_type varchar(255),
  amount bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.task_milestone_rewards IS '个人里程碑奖励';


-- 任务 / 增长预算 / R27
CREATE TABLE hhy.growth_budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period varchar(255) NOT NULL,
  reward_type varchar(255),
  budget bigint,
  consumed bigint,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.growth_budgets IS '增长预算';


-- CMS / 首页模块 / R28
CREATE TABLE hhy.home_modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  title varchar(255) NOT NULL,
  source_type varchar(255),
  config_json jsonb,
  display_order integer,
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.home_modules IS '首页模块';


-- CMS / 轮播 / R28
CREATE TABLE hhy.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position varchar(255) NOT NULL,
  title varchar(255),
  media_id bigint,
  target varchar(255),
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.banners IS '轮播';


-- CMS / 帮助/规则文章 / R28
CREATE TABLE hhy.cms_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  title varchar(255),
  content text,
  status varchar(64) NOT NULL,
  published_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.cms_articles IS '帮助/规则文章';


-- CMS / 协议 / R28
CREATE TABLE hhy.agreements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  current_version_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.agreements IS '协议';


-- CMS / 协议版本 / R28
CREATE TABLE hhy.agreement_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id bigint NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  content text,
  effective_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.agreement_versions IS '协议版本';


-- CMS / 用户同意 / R28
CREATE TABLE hhy.user_agreement_acceptances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  version_id bigint,
  scene varchar(64),
  ip varchar(64),
  device_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.user_agreement_acceptances IS '用户同意';


-- CMS / H5页面配置 / R28
CREATE TABLE hhy.h5_page_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_code varchar(255) NOT NULL,
  config_json jsonb,
  version bigint DEFAULT 0 NOT NULL,
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.h5_page_configs IS 'H5页面配置';


-- 版本 / APK下载日志 / R29
CREATE TABLE hhy.app_download_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL,
  ip varchar(64),
  source varchar(255),
  user_agent varchar(255),
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_download_logs IS 'APK下载日志';


-- 风控 / 风控规则版本 / R31
CREATE TABLE hhy.risk_rule_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  scene varchar(64),
  config_json jsonb,
  starts_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.risk_rule_versions IS '风控规则版本';


-- 风控 / 风险事件 / R31
CREATE TABLE hhy.risk_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  scene varchar(64),
  score integer,
  hits_json jsonb,
  status varchar(64) NOT NULL,
  biz_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.risk_events IS '风险事件';


-- 风控 / 设备指纹 / R31
CREATE TABLE hhy.device_fingerprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint varchar(128) NOT NULL,
  first_user_id bigint NOT NULL,
  risk_level integer,
  attributes_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.device_fingerprints IS '设备指纹';


-- 风控 / 黑名单 / R31
CREATE TABLE hhy.blacklists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  value_hash bigint NOT NULL,
  reason text,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.blacklists IS '黑名单';


-- 风控 / 白名单 / R31
CREATE TABLE hhy.whitelists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(64) NOT NULL,
  value_hash bigint NOT NULL,
  reason text,
  ends_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.whitelists IS '白名单';


-- 风控 / 人工风控复核 / R31
CREATE TABLE hhy.manual_review_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scene varchar(64) NOT NULL,
  biz_id bigint,
  status varchar(64) NOT NULL,
  assignee varchar(255),
  decision varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.manual_review_cases IS '人工风控复核';


-- 系统 / 定时任务定义 / R30
CREATE TABLE hhy.job_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  cron varchar(255) NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  config_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.job_definitions IS '定时任务定义';


-- 系统 / 任务执行日志 / R30
CREATE TABLE hhy.job_execution_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code varchar(255) NOT NULL,
  started_at timestamptz,
  finished_at timestamptz,
  status varchar(64) NOT NULL,
  error text,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.job_execution_logs IS '任务执行日志';


-- 分析 / 行为事件 / R23/R30
CREATE TABLE hhy.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  event_name varchar(255),
  biz_type varchar(255),
  biz_id bigint,
  traffic_type varchar(64),
  properties jsonb,
  occurred_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.analytics_events IS '行为事件';


-- 分析 / 每日指标 / R23/R30
CREATE TABLE hhy.daily_kpis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stat_date date NOT NULL,
  metric_code varchar(255) NOT NULL,
  dimensions jsonb,
  value bigint,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.daily_kpis IS '每日指标';


-- App构建 / 构建配置 / R29
CREATE TABLE hhy.app_build_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  environment varchar(64),
  application_id bigint,
  display_name varchar(255),
  gradle_params varchar(255),
  allowed_refs varchar(255),
  status varchar(64) NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_build_profiles IS '构建配置';


-- App构建 / 签名Profile / R29
CREATE TABLE hhy.app_signing_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  environment varchar(64),
  certificate_fingerprint varchar(128),
  secret_ref varchar(255),
  status varchar(64) NOT NULL,
  rotated_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_signing_profiles IS '签名Profile';


-- App构建 / 构建任务 / R29
CREATE TABLE hhy.app_build_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id bigint NOT NULL,
  git_ref varchar(255),
  commit_sha varchar(128),
  version_name varchar(255),
  version_code integer,
  status varchar(64) NOT NULL,
  triggered_by varchar(255),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_build_jobs IS '构建任务';


-- App构建 / 构建步骤 / R29
CREATE TABLE hhy.app_build_job_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL,
  step_code varchar(255) NOT NULL,
  sequence integer,
  status varchar(64) NOT NULL,
  log_object_key text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_build_job_steps IS '构建步骤';


-- App构建 / 构建产物 / R29
CREATE TABLE hhy.app_build_artifacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL,
  artifact_type varchar(255) NOT NULL,
  object_key text,
  file_size bigint,
  sha256 varchar(128),
  signing_fingerprint varchar(128),
  retention_until timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_build_artifacts IS '构建产物';


-- App构建 / 发布渠道 / R29
CREATE TABLE hhy.app_release_channels (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(64) NOT NULL,
  environment varchar(64) NOT NULL,
  download_domain varchar(255),
  update_policy varchar(255),
  status varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_release_channels IS '发布渠道';


-- App构建 / 发布记录 / R29
CREATE TABLE hhy.app_release_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_id bigint NOT NULL,
  channel_id bigint,
  version_name varchar(255),
  version_code integer,
  update_type varchar(255),
  status varchar(64) NOT NULL,
  published_at timestamptz,
  rollback_from_id bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_release_records IS '发布记录';


-- App构建 / 生产发布复核 / R29
CREATE TABLE hhy.app_release_approvals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_record_id bigint NOT NULL,
  applicant_id bigint,
  reviewer_id bigint,
  decision varchar(64),
  reason text,
  decided_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE hhy.app_release_approvals IS '生产发布复核';
