-- 合伙云 Pro V1.2.2：页面与运营规格新增治理数据结构
-- 该迁移补齐后台会话/MFA、受控冲正、规则模拟、通知尝试和异步导出事实。
SET search_path TO hhy, public;

-- 后台 / 后台独立登录会话与会话升级状态 / R01
CREATE TABLE IF NOT EXISTS hhy.admin_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  admin_user_id bigint NOT NULL,
  access_jti varchar(128) NOT NULL,
  refresh_hash varchar(128),
  mfa_level varchar(32) DEFAULT 'NONE' NOT NULL,
  device_fingerprint varchar(128),
  ip varchar(64),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  last_active_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_admin_sessions_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES hhy.admin_users(id),
  CONSTRAINT uq_admin_sessions_access_jti UNIQUE (access_jti),
  CONSTRAINT ck_admin_sessions_mfa_level CHECK (mfa_level IN ('NONE','VERIFIED','STEP_UP'))
);
COMMENT ON TABLE hhy.admin_sessions IS '后台独立登录会话与会话升级状态';
CREATE INDEX IF NOT EXISTS ix_admin_sessions_admin_user_id ON hhy.admin_sessions (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_device_fingerprint ON hhy.admin_sessions (device_fingerprint);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_expires_at ON hhy.admin_sessions (expires_at);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_ip ON hhy.admin_sessions (ip);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_last_active_at ON hhy.admin_sessions (last_active_at);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_refresh_hash ON hhy.admin_sessions (refresh_hash);
DROP TRIGGER IF EXISTS trg_admin_sessions_updated_at ON hhy.admin_sessions;
CREATE TRIGGER trg_admin_sessions_updated_at BEFORE UPDATE ON hhy.admin_sessions FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

-- 后台 / 管理员MFA方式和受保护密钥引用 / R01
CREATE TABLE IF NOT EXISTS hhy.admin_mfa_methods (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  admin_user_id bigint NOT NULL,
  method varchar(32) NOT NULL,
  secret_ref varchar(512),
  status varchar(32) DEFAULT 'PENDING' NOT NULL,
  confirmed_at timestamptz,
  disabled_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_admin_mfa_methods_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES hhy.admin_users(id),
  CONSTRAINT uq_admin_mfa_methods_admin_user_id_method UNIQUE (admin_user_id,method),
  CONSTRAINT ck_admin_mfa_methods_status CHECK (status IN ('PENDING','ACTIVE','DISABLED'))
);
COMMENT ON TABLE hhy.admin_mfa_methods IS '管理员MFA方式和受保护密钥引用';
CREATE INDEX IF NOT EXISTS ix_admin_mfa_methods_admin_user_id ON hhy.admin_mfa_methods (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_admin_mfa_methods_status ON hhy.admin_mfa_methods (status);
DROP TRIGGER IF EXISTS trg_admin_mfa_methods_updated_at ON hhy.admin_mfa_methods;
CREATE TRIGGER trg_admin_mfa_methods_updated_at BEFORE UPDATE ON hhy.admin_mfa_methods FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

-- 后台 / 管理员MFA恢复码哈希 / R01
CREATE TABLE IF NOT EXISTS hhy.admin_recovery_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  admin_user_id bigint NOT NULL,
  code_hash varchar(128) NOT NULL,
  used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_admin_recovery_codes_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES hhy.admin_users(id),
  CONSTRAINT uq_admin_recovery_codes_code_hash UNIQUE (code_hash)
);
COMMENT ON TABLE hhy.admin_recovery_codes IS '管理员MFA恢复码哈希';
CREATE INDEX IF NOT EXISTS ix_admin_recovery_codes_admin_user_id ON hhy.admin_recovery_codes (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_admin_recovery_codes_expires_at ON hhy.admin_recovery_codes (expires_at);

-- 后台 / 后台登录、MFA、锁定和失败安全日志 / R01
CREATE TABLE IF NOT EXISTS hhy.admin_login_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  admin_user_id bigint,
  username_masked varchar(128),
  event_type varchar(64) NOT NULL,
  result varchar(32) NOT NULL,
  failure_code varchar(64),
  ip varchar(64),
  device_fingerprint varchar(128),
  request_id varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_admin_login_logs_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES hhy.admin_users(id)
);
COMMENT ON TABLE hhy.admin_login_logs IS '后台登录、MFA、锁定和失败安全日志';
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_admin_user_id ON hhy.admin_login_logs (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_created_at ON hhy.admin_login_logs (created_at);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_device_fingerprint ON hhy.admin_login_logs (device_fingerprint);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_event_type ON hhy.admin_login_logs (event_type);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_failure_code ON hhy.admin_login_logs (failure_code);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_ip ON hhy.admin_login_logs (ip);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_request_id ON hhy.admin_login_logs (request_id);
CREATE INDEX IF NOT EXISTS ix_admin_login_logs_result ON hhy.admin_login_logs (result);

-- 账务 / 会计交易冲正申请与审批绑定 / R24
CREATE TABLE IF NOT EXISTS hhy.accounting_reversal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  source_transaction_id bigint NOT NULL,
  approval_request_id bigint NOT NULL,
  reason_code varchar(64) NOT NULL,
  reason text NOT NULL,
  evidence_json jsonb DEFAULT '[]'::jsonb,
  status varchar(32) DEFAULT 'PENDING_APPROVAL' NOT NULL,
  reversal_transaction_id bigint,
  requested_by bigint NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_accounting_reversal_requests_source_transaction_id FOREIGN KEY (source_transaction_id) REFERENCES hhy.accounting_transactions(id),
  CONSTRAINT fk_accounting_reversal_requests_approval_request_id FOREIGN KEY (approval_request_id) REFERENCES hhy.admin_approval_requests(id),
  CONSTRAINT fk_accounting_reversal_requests_reversal_transaction_id FOREIGN KEY (reversal_transaction_id) REFERENCES hhy.accounting_transactions(id),
  CONSTRAINT fk_accounting_reversal_requests_requested_by FOREIGN KEY (requested_by) REFERENCES hhy.admin_users(id),
  CONSTRAINT ck_accounting_reversal_status CHECK (status IN ('PENDING_APPROVAL','APPROVED','REJECTED','EXECUTED','CANCELLED'))
);
COMMENT ON TABLE hhy.accounting_reversal_requests IS '会计交易冲正申请与审批绑定';
CREATE INDEX IF NOT EXISTS ix_accounting_reversal_requests_created_at ON hhy.accounting_reversal_requests (created_at);
CREATE INDEX IF NOT EXISTS ix_accounting_reversal_requests_reason_code ON hhy.accounting_reversal_requests (reason_code);
CREATE INDEX IF NOT EXISTS ix_accounting_reversal_requests_requested_by ON hhy.accounting_reversal_requests (requested_by);
CREATE INDEX IF NOT EXISTS ix_accounting_reversal_requests_source_transaction_id ON hhy.accounting_reversal_requests (source_transaction_id);
CREATE INDEX IF NOT EXISTS ix_accounting_reversal_requests_status ON hhy.accounting_reversal_requests (status);
DROP TRIGGER IF EXISTS trg_accounting_reversal_requests_updated_at ON hhy.accounting_reversal_requests;
CREATE TRIGGER trg_accounting_reversal_requests_updated_at BEFORE UPDATE ON hhy.accounting_reversal_requests FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

-- 风控 / 风控规则无副作用模拟记录 / R31
CREATE TABLE IF NOT EXISTS hhy.risk_rule_simulations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  risk_rule_version_id bigint NOT NULL,
  sample_mode varchar(32) NOT NULL,
  subject_type varchar(64) NOT NULL,
  sample_hash varchar(64) NOT NULL,
  result_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  matched boolean DEFAULT false NOT NULL,
  score numeric(12,4),
  recommended_action varchar(64),
  side_effect_free boolean DEFAULT true NOT NULL,
  executed_by bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_risk_rule_simulations_risk_rule_version_id FOREIGN KEY (risk_rule_version_id) REFERENCES hhy.risk_rule_versions(id),
  CONSTRAINT ck_risk_rule_simulations_side_effect_free CHECK (side_effect_free=true),
  CONSTRAINT fk_risk_rule_simulations_executed_by FOREIGN KEY (executed_by) REFERENCES hhy.admin_users(id)
);
COMMENT ON TABLE hhy.risk_rule_simulations IS '风控规则无副作用模拟记录';
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_created_at ON hhy.risk_rule_simulations (created_at);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_executed_by ON hhy.risk_rule_simulations (executed_by);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_matched ON hhy.risk_rule_simulations (matched);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_recommended_action ON hhy.risk_rule_simulations (recommended_action);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_risk_rule_version_id ON hhy.risk_rule_simulations (risk_rule_version_id);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_sample_hash ON hhy.risk_rule_simulations (sample_hash);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_sample_mode ON hhy.risk_rule_simulations (sample_mode);
CREATE INDEX IF NOT EXISTS ix_risk_rule_simulations_subject_type ON hhy.risk_rule_simulations (subject_type);

-- 通知 / 通知每次发送尝试与供应商响应 / R30
CREATE TABLE IF NOT EXISTS hhy.notification_delivery_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  delivery_id bigint NOT NULL,
  attempt_no integer NOT NULL,
  provider varchar(64) NOT NULL,
  provider_message_id varchar(128),
  status varchar(32) NOT NULL,
  failure_code varchar(64),
  response_masked jsonb DEFAULT '{}'::jsonb,
  started_at timestamptz DEFAULT now() NOT NULL,
  finished_at timestamptz,
  CONSTRAINT fk_notification_delivery_attempts_delivery_id FOREIGN KEY (delivery_id) REFERENCES hhy.notification_deliveries(id),
  CONSTRAINT uq_notification_delivery_attempts_delivery_id_attempt_no UNIQUE (delivery_id,attempt_no)
);
COMMENT ON TABLE hhy.notification_delivery_attempts IS '通知每次发送尝试与供应商响应';
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempts_delivery_id ON hhy.notification_delivery_attempts (delivery_id);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempts_failure_code ON hhy.notification_delivery_attempts (failure_code);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempts_provider ON hhy.notification_delivery_attempts (provider);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempts_provider_message_id ON hhy.notification_delivery_attempts (provider_message_id);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempts_status ON hhy.notification_delivery_attempts (status);

-- 后台 / 高敏数据异步导出任务 / R30
CREATE TABLE IF NOT EXISTS hhy.export_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  job_no varchar(64) NOT NULL,
  export_type varchar(64) NOT NULL,
  status varchar(32) DEFAULT 'QUEUED' NOT NULL,
  filter_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
  field_codes jsonb DEFAULT '[]'::jsonb NOT NULL,
  mask_policy varchar(64) NOT NULL,
  row_limit integer NOT NULL,
  purpose text NOT NULL,
  approval_request_id bigint,
  created_by bigint NOT NULL,
  expires_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT uq_export_jobs_job_no UNIQUE (job_no),
  CONSTRAINT ck_export_jobs_row_limit CHECK (row_limit>0),
  CONSTRAINT fk_export_jobs_approval_request_id FOREIGN KEY (approval_request_id) REFERENCES hhy.admin_approval_requests(id),
  CONSTRAINT fk_export_jobs_created_by FOREIGN KEY (created_by) REFERENCES hhy.admin_users(id),
  CONSTRAINT ck_export_jobs_status CHECK (status IN ('PENDING_APPROVAL','QUEUED','RUNNING','SUCCEEDED','FAILED','EXPIRED','REJECTED'))
);
COMMENT ON TABLE hhy.export_jobs IS '高敏数据异步导出任务';
CREATE INDEX IF NOT EXISTS ix_export_jobs_approval_request_id ON hhy.export_jobs (approval_request_id);
CREATE INDEX IF NOT EXISTS ix_export_jobs_created_at ON hhy.export_jobs (created_at);
CREATE INDEX IF NOT EXISTS ix_export_jobs_created_by ON hhy.export_jobs (created_by);
CREATE INDEX IF NOT EXISTS ix_export_jobs_expires_at ON hhy.export_jobs (expires_at);
CREATE INDEX IF NOT EXISTS ix_export_jobs_export_type ON hhy.export_jobs (export_type);
CREATE INDEX IF NOT EXISTS ix_export_jobs_mask_policy ON hhy.export_jobs (mask_policy);
CREATE INDEX IF NOT EXISTS ix_export_jobs_status ON hhy.export_jobs (status);
DROP TRIGGER IF EXISTS trg_export_jobs_updated_at ON hhy.export_jobs;
CREATE TRIGGER trg_export_jobs_updated_at BEFORE UPDATE ON hhy.export_jobs FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

-- 后台 / 导出产物与完整性信息 / R30
CREATE TABLE IF NOT EXISTS hhy.export_job_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  export_job_id bigint NOT NULL,
  media_object_id bigint NOT NULL,
  file_name varchar(255) NOT NULL,
  content_type varchar(128) NOT NULL,
  size_bytes bigint NOT NULL,
  sha256 varchar(64) NOT NULL,
  row_count integer DEFAULT 0 NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_export_job_files_export_job_id FOREIGN KEY (export_job_id) REFERENCES hhy.export_jobs(id),
  CONSTRAINT fk_export_job_files_media_object_id FOREIGN KEY (media_object_id) REFERENCES hhy.media_objects(id),
  CONSTRAINT ck_export_job_files_size_bytes CHECK (size_bytes>=0),
  CONSTRAINT uq_export_job_files_sha256 UNIQUE (sha256),
  CONSTRAINT ck_export_job_files_row_count CHECK (row_count>=0)
);
COMMENT ON TABLE hhy.export_job_files IS '导出产物与完整性信息';
CREATE INDEX IF NOT EXISTS ix_export_job_files_expires_at ON hhy.export_job_files (expires_at);
CREATE INDEX IF NOT EXISTS ix_export_job_files_export_job_id ON hhy.export_job_files (export_job_id);

-- 后台 / 导出文件一次性令牌和下载审计 / R30
CREATE TABLE IF NOT EXISTS hhy.export_download_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  export_job_file_id bigint NOT NULL,
  admin_user_id bigint NOT NULL,
  token_hash varchar(128) NOT NULL,
  purpose text NOT NULL,
  ip varchar(64),
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  result varchar(32) DEFAULT 'ISSUED' NOT NULL,
  request_id varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT fk_export_download_logs_export_job_file_id FOREIGN KEY (export_job_file_id) REFERENCES hhy.export_job_files(id),
  CONSTRAINT fk_export_download_logs_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES hhy.admin_users(id),
  CONSTRAINT uq_export_download_logs_token_hash UNIQUE (token_hash),
  CONSTRAINT ck_export_download_logs_result CHECK (result IN ('ISSUED','DOWNLOADED','EXPIRED','REJECTED','FAILED'))
);
COMMENT ON TABLE hhy.export_download_logs IS '导出文件一次性令牌和下载审计';
CREATE INDEX IF NOT EXISTS ix_export_download_logs_admin_user_id ON hhy.export_download_logs (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_created_at ON hhy.export_download_logs (created_at);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_expires_at ON hhy.export_download_logs (expires_at);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_export_job_file_id ON hhy.export_download_logs (export_job_file_id);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_ip ON hhy.export_download_logs (ip);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_request_id ON hhy.export_download_logs (request_id);
CREATE INDEX IF NOT EXISTS ix_export_download_logs_result ON hhy.export_download_logs (result);

