-- R24 durable payout account, withdrawal quote and finance workflow facts.
SET search_path TO hhy, public;

ALTER TABLE hhy.payout_accounts
  ALTER COLUMN account_cipher TYPE text USING account_cipher::text,
  ALTER COLUMN account_hash TYPE varchar(64) USING account_hash::text,
  ALTER COLUMN real_name TYPE text;

ALTER TABLE hhy.payout_accounts
  ADD COLUMN IF NOT EXISTS account_masked varchar(64);

-- Legacy integer placeholders are not decryptable account data and must be rebound.
UPDATE hhy.payout_accounts
SET status = 'DISABLED', account_masked = NULL
WHERE account_cipher !~ '^hhy-r24-payout-v1\.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_payout_accounts_user_id
  ON hhy.payout_accounts (user_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_payout_accounts_hash
  ON hhy.payout_accounts (account_hash)
  WHERE account_hash IS NOT NULL AND status = 'ACTIVE';

CREATE TABLE IF NOT EXISTS hhy.withdrawal_quotes (
  id varchar(64) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES hhy.users(id) ON DELETE RESTRICT,
  payout_account_id bigint NOT NULL REFERENCES hhy.payout_accounts(id) ON DELETE RESTRICT,
  amount bigint NOT NULL,
  fee bigint NOT NULL,
  net_amount bigint NOT NULL,
  status varchar(32) DEFAULT 'ACTIVE' NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT ck_r24_withdrawal_quote_amounts CHECK (
    amount > 0 AND fee >= 0 AND net_amount = amount - fee AND net_amount > 0),
  CONSTRAINT ck_r24_withdrawal_quote_status CHECK (status IN ('ACTIVE','CONSUMED','EXPIRED')),
  CONSTRAINT ck_r24_withdrawal_quote_lifecycle CHECK (
    (status = 'ACTIVE' AND consumed_at IS NULL) OR
    (status = 'CONSUMED' AND consumed_at IS NOT NULL) OR
    (status = 'EXPIRED' AND consumed_at IS NULL)),
  CONSTRAINT ck_r24_withdrawal_quote_expiry CHECK (expires_at > created_at),
  CONSTRAINT ck_r24_withdrawal_quote_version CHECK (version >= 0)
);
CREATE INDEX IF NOT EXISTS ix_r24_withdrawal_quotes_user_expiry
  ON hhy.withdrawal_quotes (user_id, expires_at DESC);
DROP TRIGGER IF EXISTS trg_r24_withdrawal_quotes_updated_at ON hhy.withdrawal_quotes;
CREATE TRIGGER trg_r24_withdrawal_quotes_updated_at
  BEFORE UPDATE ON hhy.withdrawal_quotes
  FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

ALTER TABLE hhy.withdrawal_requests
  ADD COLUMN IF NOT EXISTS quote_id varchar(64),
  ADD COLUMN IF NOT EXISTS payout_account_id bigint,
  ADD COLUMN IF NOT EXISTS failure_code varchar(64),
  ADD COLUMN IF NOT EXISTS completed_at timestamptz;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_r24_withdrawal_quote_id') THEN
    ALTER TABLE hhy.withdrawal_requests ADD CONSTRAINT fk_r24_withdrawal_quote_id
    FOREIGN KEY (quote_id) REFERENCES hhy.withdrawal_quotes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_r24_withdrawal_payout_account_id') THEN
    ALTER TABLE hhy.withdrawal_requests ADD CONSTRAINT fk_r24_withdrawal_payout_account_id
    FOREIGN KEY (payout_account_id) REFERENCES hhy.payout_accounts(id) ON DELETE RESTRICT;
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_withdrawal_number
  ON hhy.withdrawal_requests (withdraw_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_withdrawal_quote
  ON hhy.withdrawal_requests (quote_id) WHERE quote_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_payout_transactions_withdrawal
  ON hhy.payout_transactions (withdrawal_id);

CREATE TABLE IF NOT EXISTS hhy.withdrawal_review_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_id bigint NOT NULL REFERENCES hhy.withdrawal_requests(id) ON DELETE RESTRICT,
  stage varchar(32) NOT NULL,
  decision varchar(32) NOT NULL,
  reason text NOT NULL,
  evidence_json jsonb DEFAULT '[]'::jsonb NOT NULL,
  from_status varchar(64) NOT NULL,
  to_status varchar(64) NOT NULL,
  actor_admin_id bigint NOT NULL REFERENCES hhy.admin_users(id) ON DELETE RESTRICT,
  request_id varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT ck_r24_withdrawal_review_stage CHECK (stage IN ('RISK','FINANCE')),
  CONSTRAINT ck_r24_withdrawal_review_decision CHECK (decision IN ('APPROVE','REJECT','ESCALATE'))
);
CREATE INDEX IF NOT EXISTS ix_r24_withdrawal_review_events_withdrawal
  ON hhy.withdrawal_review_events (withdrawal_id, created_at, id);

CREATE TABLE IF NOT EXISTS hhy.reward_adjustment_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES hhy.users(id) ON DELETE RESTRICT,
  direction varchar(16) NOT NULL,
  amount bigint NOT NULL,
  reason text NOT NULL,
  business_ref varchar(255),
  approval_request_id bigint NOT NULL REFERENCES hhy.admin_approval_requests(id) ON DELETE RESTRICT,
  requested_by bigint NOT NULL REFERENCES hhy.admin_users(id) ON DELETE RESTRICT,
  status varchar(32) DEFAULT 'PENDING_APPROVAL' NOT NULL,
  version bigint DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT ck_r24_reward_adjustment_direction CHECK (direction IN ('CREDIT','DEBIT')),
  CONSTRAINT ck_r24_reward_adjustment_amount CHECK (amount > 0),
  CONSTRAINT ck_r24_reward_adjustment_status CHECK (
    status IN ('PENDING_APPROVAL','APPROVED','REJECTED','EXECUTED','CANCELLED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_reward_adjustment_business_ref
  ON hhy.reward_adjustment_requests (business_ref) WHERE business_ref IS NOT NULL;
DROP TRIGGER IF EXISTS trg_r24_reward_adjustment_requests_updated_at ON hhy.reward_adjustment_requests;
CREATE TRIGGER trg_r24_reward_adjustment_requests_updated_at
  BEFORE UPDATE ON hhy.reward_adjustment_requests
  FOR EACH ROW EXECUTE FUNCTION hhy.set_updated_at();

CREATE UNIQUE INDEX IF NOT EXISTS uq_r24_accounting_reversal_source_active
  ON hhy.accounting_reversal_requests (source_transaction_id)
  WHERE status IN ('PENDING_APPROVAL','APPROVED');

ALTER TABLE hhy.accounting_transactions
  ADD COLUMN IF NOT EXISTS currency varchar(3) DEFAULT 'CNY' NOT NULL,
  ADD COLUMN IF NOT EXISTS version bigint DEFAULT 0 NOT NULL;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_r24_accounting_transaction_currency') THEN
    ALTER TABLE hhy.accounting_transactions ADD CONSTRAINT ck_r24_accounting_transaction_currency CHECK (currency = 'CNY');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_r24_accounting_transaction_version') THEN
    ALTER TABLE hhy.accounting_transactions ADD CONSTRAINT ck_r24_accounting_transaction_version CHECK (version >= 0);
  END IF;
END $$;

INSERT INTO hhy.ledger_accounts(account_no, account_type, currency, owner_id, owner_type, status)
VALUES
  ('R24-REWARD-LIABILITY', 'LIABILITY', 'CNY', 'PLATFORM', 'PLATFORM', 'ACTIVE'),
  ('R24-PAYOUT-CASH', 'ASSET', 'CNY', 'PLATFORM', 'PLATFORM', 'ACTIVE'),
  ('R24-WITHDRAWAL-FEE-REVENUE', 'REVENUE', 'CNY', 'PLATFORM', 'PLATFORM', 'ACTIVE')
ON CONFLICT (account_no) DO NOTHING;

INSERT INTO hhy.system_configs(key, value_json, version, scope) VALUES
  ('system.withdrawal.enabled', 'true'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.min_amount_cent.normal', '1000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.fixed_cent.normal', '100'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.bps.normal', '0'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_count.normal', '1'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.max_amount_cent.normal', '500000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_total_cent.normal', '1000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.monthly_total_cent.normal', '10000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.min_amount_cent.month', '500'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.fixed_cent.month', '50'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.bps.month', '0'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_count.month', '2'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.max_amount_cent.month', '500000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_total_cent.month', '1000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.monthly_total_cent.month', '10000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.min_amount_cent.quarter', '300'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.fixed_cent.quarter', '30'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.bps.quarter', '0'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_count.quarter', '3'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.max_amount_cent.quarter', '500000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_total_cent.quarter', '1000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.monthly_total_cent.quarter', '10000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.min_amount_cent.year', '100'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.fixed_cent.year', '0'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.fee.bps.year', '0'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_count.year', '5'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.max_amount_cent.year', '500000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.daily_total_cent.year', '1000000'::jsonb, 0, 'GLOBAL'),
  ('withdrawal.monthly_total_cent.year', '10000000'::jsonb, 0, 'GLOBAL')
ON CONFLICT (key, scope) DO NOTHING;

COMMENT ON COLUMN hhy.payout_accounts.account_cipher IS
  'AES-256-GCM envelope; plaintext payout account identifiers are never persisted';
COMMENT ON TABLE hhy.withdrawal_quotes IS
  'Immutable fee snapshot consumed exactly once by a withdrawal request';
COMMENT ON TABLE hhy.withdrawal_review_events IS
  'Append-only risk and finance review evidence for withdrawal state transitions';
COMMENT ON TABLE hhy.reward_adjustment_requests IS
  'Two-person approval request for manual reward balance adjustments';
