package cc.orbexa.hhy.content;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

// Generated by scripts/generate_chat_report_reason_catalog.py. Do not edit.
public final class R14ChatReportReasonCatalog {
    public record Option(String code, String label, boolean enabled, int order) {}

    public static final List<Option> OPTIONS = List.of(
            new Option("HARASSMENT", "骚扰", true, 10),
            new Option("DUPLICATE_BULK_MESSAGE", "相同文案批量发送", true, 20),
            new Option("DANGEROUS_LINK", "危险链接", true, 30)
    );
    private static final Set<String> ENABLED_CODES = OPTIONS.stream()
            .filter(Option::enabled).map(Option::code).collect(Collectors.toUnmodifiableSet());

    private R14ChatReportReasonCatalog() {}

    public static boolean isEnabled(String code) {
        return code != null && ENABLED_CODES.contains(code);
    }
}
