<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import StatusNotice from '../components/StatusNotice.vue'
import { adminContentsApi, isApiRequestError, type AdminContentDictionaryPage } from '../services'
const result = ref<AdminContentDictionaryPage>(); const loading = ref(true); const refreshing = ref(false); const error = ref<string>(); const offline = ref(!navigator.onLine); const keyword = ref(''); let request: AbortController | undefined
const items = computed(() => result.value?.items ?? [])
async function load(mode: 'initial'|'refresh' = 'initial') { request?.abort(); request = new AbortController(); if (!navigator.onLine) { offline.value = true; loading.value = false; error.value = '当前设备离线，请恢复网络后重试'; return } offline.value = false; error.value = undefined; if (mode === 'initial') loading.value = true; else refreshing.value = true; try { result.value = await adminContentsApi.dictionaries({ page: 1, pageSize: 100, keyword: keyword.value.trim() || undefined }, { signal: request.signal }) } catch (caught) { error.value = isApiRequestError(caught) ? caught.message : '字典暂时无法加载，请稍后重试' } finally { loading.value = false; refreshing.value = false } }
function updateOnline() { offline.value = !navigator.onLine; if (navigator.onLine && !result.value) void load() }
onMounted(() => { window.addEventListener('online', updateOnline); window.addEventListener('offline', updateOnline); void load() }); onBeforeUnmount(() => { request?.abort(); window.removeEventListener('online', updateOnline); window.removeEventListener('offline', updateOnline) })
</script>
<template><article class="page users-page"><header class="page-heading"><div><div class="eyebrow">内容配置</div><h1>字典与属性</h1><p>维护地区、平台、人数和标签等内容字典。</p></div><button class="ghost-button" :disabled="refreshing || offline" @click="load('refresh')">{{ refreshing ? '刷新中…' : '刷新' }}</button></header><StatusNotice v-if="offline" tone="warning" title="当前设备离线" detail="恢复网络后可重新读取字典。" /><form class="card user-filters" @submit.prevent="load('refresh')"><label class="field"><span class="field-label">关键词</span><input v-model="keyword" class="input" maxlength="100" placeholder="字典代码或名称" /></label><button class="primary-button" :disabled="offline">查询</button></form><section v-if="loading" class="card skeleton-stack"><div v-for="n in 6" :key="n" class="skeleton user-row-skeleton" /></section><section v-else-if="error && !result" class="card error-state"><h2>字典暂时无法加载</h2><p>{{ error }}</p><button class="primary-button" :disabled="offline" @click="load()">重新加载</button></section><section v-else-if="items.length === 0" class="card empty-state"><h2>暂无字典数据</h2><p>调整关键词后重新查询。</p></section><section v-else class="card user-table-card"><div class="user-table-wrap"><table class="user-table"><thead><tr><th>代码</th><th>名称</th><th>状态</th><th>版本</th><th>更新时间</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.id }}</td><td>{{ item.title }}</td><td><span class="status-chip">{{ item.status }}</span></td><td>v{{ item.version }}</td><td>{{ item.updatedAt || '暂无' }}</td></tr></tbody></table></div></section></article></template>
