<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusNotice from '../components/StatusNotice.vue'
import { adminRedPacketApi, adminSession, isApiRequestError, type AdminRedPacketPage, type AdminRedPacketResource, type AdminRedPacketReview } from '../services'

type ReviewConfirmation = { campaignId: string; version: number; body: AdminRedPacketReview; idempotencyKey: string }
const route = useRoute(); const router = useRouter(); const items = ref<AdminRedPacketResource[]>([]); const pageMeta = ref<AdminRedPacketPage['page']>(); const selected = ref<AdminRedPacketResource>(); const confirmation = ref<ReviewConfirmation>(); const loading = ref(true); const detailLoading = ref(false); const submitting = ref(false); const error = ref(''); const forbidden = ref(false); const stale = ref(false); const notice = ref('')
const filters = reactive({ page: Number(route.query.page) || 1, pageSize: Number(route.query.pageSize) || 20, status: String(route.query.status ?? 'PRE_REVIEWING'), keyword: String(route.query.keyword ?? ''), sort: 'priority:desc,createdAt:asc' })
const decision = reactive<{ decision: 'APPROVE' | 'REJECT' | 'ESCALATE'; reason: string; evidenceIds: string }>({ decision: 'APPROVE', reason: '', evidenceIds: '' })
const canReview = computed(() => adminSession.hasPermission('redpacket.review')); const total = computed(() => Number(pageMeta.value?.total ?? items.value.length)); const hasMore = computed(() => String(pageMeta.value?.hasMore) === 'true')
function money(value?: number) { return value === undefined ? '暂无' : new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(value / 100) }
function statusLabel(value: string) { return ({ DRAFT: '草稿', PRE_REVIEWING: '预审核中', PRE_REVIEW_REJECTED: '预审核未通过', PRE_REVIEW_APPROVED: '预审核已通过', WAITING_PAYMENT: '待支付', PAYMENT_PROCESSING: '支付处理中', ACTIVE: '进行中', PAUSED_BY_CONTENT_OFFLINE: '内容下线暂停', PAUSED_BY_OWNER: '发起人暂停', PAUSED_BY_RISK: '风控暂停', SOLD_OUT: '已领完', CLOSED_BY_OWNER: '已关闭', TERMINATED_BY_PLATFORM: '平台终止' } as Record<string, string>)[value] ?? '状态待确认' }
function decisionLabel(value: string) { return ({ APPROVE: '通过', REJECT: '驳回', ESCALATE: '转二审' } as Record<string, string>)[value] }
function message(caught: unknown) { if (isApiRequestError(caught)) { if (caught.status === 401) adminSession.clear(); if (caught.status === 403) forbidden.value = true; stale.value = caught.status === 409; return caught.message } return '红包预审核暂时无法加载，请稍后重试' }
async function syncQuery() { await router.replace({ query: { ...route.query, campaignId: selected.value?.id || route.query.campaignId, page: String(filters.page), pageSize: String(filters.pageSize), status: filters.status || undefined, keyword: filters.keyword || undefined, sort: filters.sort } }) }
async function load() { loading.value = true; error.value = ''; try { await syncQuery(); const page = await adminRedPacketApi.campaigns(filters); items.value = page.items; pageMeta.value = page.page; const queryId = String(route.query.campaignId ?? ''); const item = items.value.find((value) => value.id === queryId); if (item) await openDetail(item) } catch (caught) { error.value = message(caught) } finally { loading.value = false } }
async function openDetail(item: AdminRedPacketResource) { selected.value = item; await router.replace({ query: { ...route.query, campaignId: item.id } }); detailLoading.value = true; try { selected.value = await adminRedPacketApi.campaign(item.id); stale.value = false } catch (caught) { error.value = message(caught) } finally { detailLoading.value = false } }
function goToPage(page: number) { if (page < 1 || loading.value || (page > filters.page && !hasMore.value)) return; filters.page = page; void load() }
function openConfirmation() { if (!selected.value || !canReview.value || !decision.reason.trim()) { notice.value = '审核原因不能为空，且当前会话必须拥有 redpacket.review 权限。'; return } const evidenceIds = [...new Set(decision.evidenceIds.split(',').map((value) => value.trim()).filter(Boolean))]; if (evidenceIds.length > 100) { notice.value = '审核证据最多 100 项，请精简后再提交。'; return } confirmation.value = { campaignId: selected.value.id, version: selected.value.version, body: { decision: decision.decision, reason: decision.reason.trim(), expectedVersion: selected.value.version, evidenceIds }, idempotencyKey: `r20-review-${selected.value.id}-${selected.value.version}-${Date.now().toString(36)}` }; notice.value = '' }
function closeConfirmation() { if (!submitting.value) confirmation.value = undefined }
async function submitConfirmed() { const target = confirmation.value; if (!target || !canReview.value) return; submitting.value = true; notice.value = ''; try { const data = await adminRedPacketApi.review(target.campaignId, target.body, target.idempotencyKey); if ('status' in data) { selected.value = data as AdminRedPacketResource; items.value = items.value.map((item) => item.id === selected.value?.id ? selected.value! : item); notice.value = `已提交${decisionLabel(target.body.decision)}，服务端版本已更新。`; confirmation.value = undefined } } catch (caught) { error.value = message(caught) } finally { submitting.value = false } }
onMounted(() => { void load() })
</script>

<template>
  <article class="page review-page"><header class="page-heading"><div><div class="eyebrow">红包运营</div><h1>红包预审核</h1><p>按优先级处理真实活动，决定与服务端版本、证据编号和审计上下文绑定。</p></div><button class="ghost-button" :disabled="loading" @click="load">刷新队列</button></header>
    <StatusNotice v-if="forbidden" tone="danger" title="没有红包审核读取权限" detail="当前会话不会泄露待审核活动。" /><StatusNotice v-if="error" tone="danger" title="操作未完成" :detail="error" /><StatusNotice v-if="notice" tone="success" title="审核状态" :detail="notice" /><StatusNotice v-if="stale" tone="warning" title="任务版本已变化" detail="已拒绝覆盖，请刷新后重新核对事实。" />
    <form class="review-filters" @submit.prevent="filters.page = 1; load()"><label class="field"><span class="field-label">关键词</span><input v-model="filters.keyword" class="input" maxlength="100" placeholder="活动 ID 或内容 ID" /></label><label class="field"><span class="field-label">状态</span><select v-model="filters.status" class="input"><option value="PRE_REVIEWING">待预审核</option><option value="PRE_REVIEW_APPROVED">预审核已通过</option><option value="PRE_REVIEW_REJECTED">预审核未通过</option><option value="">全部状态</option></select></label><span class="review-live-indicator">优先处理 · 先提交先审</span><button class="primary-button" :disabled="loading">应用筛选</button></form>
    <section class="review-workbench"><section class="review-pane review-queue-pane"><div class="review-pane-heading"><div><h2>审核队列</h2><p>第 {{ filters.page }} 页 · 共 {{ total }} 项</p></div></div><div v-if="loading" class="loading-state">正在加载预审核队列…</div><div v-else-if="!items.length" class="review-pane-state"><strong>当前没有待预审核活动</strong><p>调整筛选后重新查询，状态来自服务端。</p></div><table v-else class="review-table"><thead><tr><th>活动</th><th>金额</th><th>状态</th><th>版本</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" :class="{ selected: selected?.id === item.id }" @click="openDetail(item)"><td><strong>{{ item.id }}</strong><small>内容 {{ item.contentId || '暂无' }}</small></td><td>{{ money(item.principalCent) }}</td><td><span class="status-chip" :data-status="item.status">{{ statusLabel(item.status) }}</span></td><td>v{{ item.version }}</td></tr></tbody></table><footer v-if="!loading && total > 0" class="review-pagination"><span>当前页 {{ items.length }} 项</span><div><button type="button" class="ghost-button" :disabled="filters.page <= 1" @click="goToPage(filters.page - 1)">上一页</button><button type="button" class="ghost-button" :disabled="!hasMore" @click="goToPage(filters.page + 1)">下一页</button></div></footer></section>
      <section class="review-pane review-context-pane"><div class="review-pane-heading"><div><h2>任务上下文</h2><p>业务对象、金额与版本</p></div></div><div v-if="!selected" class="review-pane-state"><strong>从队列选择一项活动</strong><p>详情加载后才显示决定入口。</p></div><div v-else-if="detailLoading" class="loading-state">正在加载最新活动…</div><template v-else><dl class="review-facts"><div><dt>活动 ID</dt><dd>{{ selected.id }}</dd></div><div><dt>内容 ID</dt><dd>{{ selected.contentId || '暂无' }}</dd></div><div><dt>状态</dt><dd>{{ statusLabel(selected.status) }}</dd></div><div><dt>总数量</dt><dd>{{ selected.totalCount }}</dd></div><div><dt>本金</dt><dd>{{ money(selected.principalCent) }}</dd></div><div><dt>版本</dt><dd>v{{ selected.version }}</dd></div></dl><section class="review-context-section"><h3>详情 Tab</h3><p>概览 · 业务数据 · 状态历史 · 关联对象 · 操作审计</p><p class="dialog-note">仅展示接口实际返回字段；手机号、支付账号、IP 和风控细节不在本页生成。</p></section></template></section>
      <aside class="review-pane review-decision-pane"><div class="review-pane-heading"><div><h2>处理决定</h2><p>写操作绑定最新版本</p></div></div><div v-if="!selected" class="review-pane-state"><strong>尚未选择活动</strong></div><template v-else><StatusNotice v-if="!canReview" tone="warning" title="当前会话只读" detail="需要 redpacket.review 权限。" /><form class="review-action-form" @submit.prevent="openConfirmation"><label class="field"><span class="field-label">决定</span><select v-model="decision.decision" class="input"><option value="APPROVE">通过</option><option value="REJECT">驳回</option><option value="ESCALATE">转二审</option></select></label><label class="field"><span class="field-label">原因</span><textarea v-model="decision.reason" class="input" maxlength="2000" placeholder="说明证据判断与处置依据" /></label><label class="field"><span class="field-label">证据编号</span><input v-model="decision.evidenceIds" class="input" maxlength="2000" placeholder="多个编号以逗号分隔" /></label><button class="primary-button review-full-button" :disabled="submitting || !canReview || stale || selected.status !== 'PRE_REVIEWING'">核对并继续</button><small>提交前会展示目标、影响、原因和服务端版本；409 不会盲重试。</small></form></template></aside></section>
    <div v-if="confirmation" class="modal-backdrop" role="presentation" @click.self="closeConfirmation"><section class="modal review-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="red-packet-review-confirm-title"><header class="modal-header"><div><h2 id="red-packet-review-confirm-title">确认提交红包预审核</h2><p>请核对目标、影响、原因、审批要求和服务端版本。提交后将触发通知与审计。</p></div><button class="icon-button" aria-label="关闭确认窗口" :disabled="submitting" @click="closeConfirmation">×</button></header><dl class="review-confirm-facts"><div><dt>目标活动</dt><dd>{{ confirmation.campaignId }}</dd></div><div><dt>服务端版本</dt><dd>v{{ confirmation.version }}</dd></div><div><dt>处理决定</dt><dd>{{ decisionLabel(confirmation.body.decision) }}</dd></div><div><dt>影响</dt><dd>更新红包预审核状态并写入审计记录</dd></div><div><dt>原因</dt><dd>{{ confirmation.body.reason }}</dd></div><div><dt>审批要求</dt><dd>普通预审核无需额外审批；高风险后续动作仍按独立权限执行</dd></div><div><dt>通知</dt><dd>结果将通知活动发起人并进入操作审计</dd></div></dl><StatusNotice tone="warning" title="提交前最后检查" detail="审核决定不可直接修改；版本冲突时系统会拒绝覆盖并保留当前输入。" /><footer class="modal-footer"><button class="ghost-button" :disabled="submitting" @click="closeConfirmation">取消</button><button :class="confirmation.body.decision === 'REJECT' ? 'danger-button' : 'primary-button'" :disabled="submitting" @click="submitConfirmed">{{ submitting ? '提交中…' : '确认并提交' }}</button></footer></section></div>
  </article>
</template>
