<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusNotice from '../components/StatusNotice.vue'
import { adminRedPacketApi, adminSession, isApiRequestError, type AdminRedPacketPage, type AdminRedPacketResource } from '../services'

const route = useRoute(); const router = useRouter()
const items = ref<AdminRedPacketResource[]>([]); const pageMeta = ref<AdminRedPacketPage['page']>(); const selected = ref<AdminRedPacketResource>(); const loading = ref(true); const error = ref(''); const forbidden = ref(false); const detailLoading = ref(false)
const filters = reactive({ page: Number(route.query.page) || 1, pageSize: Number(route.query.pageSize) || 20, keyword: String(route.query.keyword ?? ''), status: String(route.query.status ?? ''), sort: String(route.query.sort ?? 'createdAt:desc') })
const total = computed(() => Number(pageMeta.value?.total ?? items.value.length)); const hasMore = computed(() => String(pageMeta.value?.hasMore) === 'true'); const active = computed(() => items.value.filter((item) => item.status === 'ACTIVE').length); const review = computed(() => items.value.filter((item) => item.status === 'PRE_REVIEWING').length)
function money(value?: number) { return value === undefined ? '暂无' : new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(value / 100) }
function time(value?: string) { return value ? value.slice(0, 16).replace('T', ' ') : '暂无' }
function statusLabel(value: string) { return ({ DRAFT: '草稿', PRE_REVIEWING: '预审核中', PRE_REVIEW_REJECTED: '预审核未通过', PRE_REVIEW_APPROVED: '预审核已通过', WAITING_PAYMENT: '待支付', PAYMENT_PROCESSING: '支付处理中', ACTIVE: '进行中', PAUSED_BY_CONTENT_OFFLINE: '内容下线暂停', PAUSED_BY_OWNER: '发起人暂停', PAUSED_BY_RISK: '风控暂停', SOLD_OUT: '已领完', CLOSED_BY_OWNER: '已关闭', TERMINATED_BY_PLATFORM: '平台终止' } as Record<string, string>)[value] ?? '状态待确认' }
function message(caught: unknown) { if (isApiRequestError(caught)) { if (caught.status === 401) adminSession.clear(); if (caught.status === 403) forbidden.value = true; return caught.message } return '红包活动暂时无法加载，请稍后重试' }
async function syncQuery() { await router.replace({ query: { page: String(filters.page), pageSize: String(filters.pageSize), keyword: filters.keyword || undefined, status: filters.status || undefined, sort: filters.sort } }) }
async function load() { loading.value = true; error.value = ''; forbidden.value = false; try { await syncQuery(); const page = await adminRedPacketApi.campaigns(filters); items.value = page.items; pageMeta.value = page.page; if (selected.value) selected.value = items.value.find((item) => item.id === selected.value?.id) } catch (caught) { error.value = message(caught) } finally { loading.value = false } }
async function openDetail(item: AdminRedPacketResource) { await router.push({ name: 'ADM-RP-002', params: { id: item.id } }) }
function goToPage(page: number) { if (page < 1 || loading.value || (page > filters.page && !hasMore.value)) return; filters.page = page; void load() }
function reset() { Object.assign(filters, { page: 1, pageSize: 20, keyword: '', status: '', sort: 'createdAt:desc' }); void load() }
onMounted(() => { void load() })
</script>

<template>
  <article class="page red-packet-page">
    <header class="page-heading"><div><div class="eyebrow">红包运营</div><h1>红包活动</h1><p>查看真实活动状态、金额与服务端版本，详情保留业务数据与审计上下文。</p></div><button class="ghost-button" :disabled="loading" @click="load">{{ loading ? '刷新中…' : '刷新数据' }}</button></header>
    <StatusNotice v-if="forbidden" tone="danger" title="没有红包读取权限" detail="需要 redpacket.read 权限，页面不会泄露资源是否存在。" />
    <StatusNotice v-if="error" tone="danger" title="操作未完成" :detail="error" />
    <section class="order-metrics"><div><span>符合筛选</span><strong>{{ total }}</strong><small>服务端总数</small></div><div><span>进行中</span><strong>{{ active }}</strong><small>当前页</small></div><div><span>待审核</span><strong>{{ review }}</strong><small>当前页</small></div><div><span>读取权限</span><strong>{{ adminSession.hasPermission('redpacket.read') ? '可用' : '只读' }}</strong><small>当前会话</small></div></section>
    <form class="card order-filters" @submit.prevent="filters.page = 1; load()"><label class="field"><span class="field-label">关键词</span><input v-model="filters.keyword" class="input" maxlength="100" placeholder="活动 ID 或内容 ID" /></label><label class="field"><span class="field-label">状态</span><select v-model="filters.status" class="input"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="PRE_REVIEWING">预审核中</option><option value="PRE_REVIEW_REJECTED">预审核未通过</option><option value="PRE_REVIEW_APPROVED">预审核已通过</option><option value="WAITING_PAYMENT">待支付</option><option value="PAYMENT_PROCESSING">支付处理中</option><option value="ACTIVE">进行中</option><option value="PAUSED_BY_CONTENT_OFFLINE">内容下线暂停</option><option value="PAUSED_BY_OWNER">发起人暂停</option><option value="PAUSED_BY_RISK">风控暂停</option><option value="SOLD_OUT">已领完</option><option value="CLOSED_BY_OWNER">已关闭</option><option value="TERMINATED_BY_PLATFORM">平台终止</option></select></label><label class="field"><span class="field-label">排序</span><select v-model="filters.sort" class="input"><option value="createdAt:desc">最近创建</option><option value="createdAt:asc">最早创建</option><option value="updatedAt:desc">最近更新</option></select></label><button class="primary-button" :disabled="loading">应用筛选</button><button class="ghost-button" type="button" @click="reset">重置</button></form>
    <section class="card table-card"><div v-if="loading" class="loading-state">正在加载红包活动…</div><div v-else-if="!items.length" class="empty-state">暂无符合条件的红包活动，请调整筛选后重试。</div><div v-else class="red-packet-table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>内容 ID</th><th>发起用户</th><th>状态</th><th>红包总数量</th><th>剩余数量</th><th>单个金额</th><th>本金</th><th>服务费</th><th>开始时间</th><th>结束时间</th><th>版本</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" :class="{ selected: selected?.id === item.id }"><td><strong>{{ item.id }}</strong></td><td>{{ item.contentId || '暂无' }}</td><td>{{ item.ownerUserId || '脱敏' }}</td><td><span class="status-chip" :data-status="item.status">{{ statusLabel(item.status) }}</span></td><td>{{ item.totalCount }}</td><td>{{ item.remainingCount }}</td><td>{{ money(item.amountPerClaimCent) }}</td><td>{{ money(item.principalCent) }}</td><td>{{ money(item.serviceFeeCent) }}</td><td>{{ time(item.startAt) }}</td><td>{{ time(item.endAt) }}</td><td>v{{ item.version }}</td><td><button type="button" class="secondary-button" @click="openDetail(item)">查看详情</button></td></tr></tbody></table></div><footer v-if="!loading && total > 0" class="pagination"><span>第 {{ filters.page }} 页，共 {{ total }} 条</span><button type="button" class="ghost-button" :disabled="filters.page <= 1" @click="goToPage(filters.page - 1)">上一页</button><button type="button" class="ghost-button" :disabled="!hasMore" @click="goToPage(filters.page + 1)">下一页</button></footer></section>
    <section v-if="selected" class="card detail-card"><header class="page-heading"><div><div class="eyebrow">活动详情</div><h2>{{ selected.id }}</h2><p>详情 Tab：概览 · 业务数据 · 状态历史 · 关联对象 · 操作审计</p></div><button class="icon-button" aria-label="关闭详情" @click="selected = undefined">×</button></header><div v-if="detailLoading" class="loading-state">正在加载最新版本…</div><dl v-else class="detail-facts"><div><dt>内容 ID</dt><dd>{{ selected.contentId || '暂无' }}</dd></div><div><dt>状态</dt><dd>{{ statusLabel(selected.status) }}</dd></div><div><dt>本金</dt><dd>{{ money(selected.principalCent) }}</dd></div><div><dt>服务费</dt><dd>{{ money(selected.serviceFeeCent) }}</dd></div><div><dt>库存</dt><dd>{{ selected.remainingCount }} / {{ selected.totalCount }}</dd></div><div><dt>服务端版本</dt><dd>v{{ selected.version }}</dd></div></dl><p class="dialog-note">资金账本、会话和领取明细需 redpacket.finance 等独立权限；本页不推测或展示未返回字段。</p></section>
  </article>
</template>
