<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusNotice from '../components/StatusNotice.vue'
import { adminPropsApi, adminSession, isApiRequestError, type AdminPropResource } from '../services'
const route = useRoute(); const router = useRouter(); const items = ref<AdminPropResource[]>([]); const loading = ref(true); const error = ref(''); const conflict = ref(''); const creating = ref(false)
const canWrite = computed(() => adminSession.hasPermission('prop.slot.write'))
const filters = reactive({ page: Number(route.query.page) || 1, pageSize: Number(route.query.pageSize) || 20, keyword: String(route.query.keyword ?? ''), status: String(route.query.status ?? ''), sort: String(route.query.sort ?? 'createdAt:desc') })
const form = reactive({ pageCode: '', slotCode: '', capacity: 1, reason: '' })
function config(item: AdminPropResource) { return (item.configuration ?? {}) as Record<string, unknown> }
function statusLabel(value: string) { return value === 'ACTIVE' ? '开放' : value === 'INACTIVE' ? '停用' : '待确认' }
function message(caught: unknown) { if (isApiRequestError(caught)) { if (caught.status === 401) adminSession.clear(); return caught.message } return '资源位暂时无法加载，请稍后重试' }
async function syncQuery() { await router.replace({ query: { page: String(filters.page), pageSize: String(filters.pageSize), keyword: filters.keyword || undefined, status: filters.status || undefined, sort: filters.sort } }) }
async function load() { loading.value = true; error.value = ''; try { await syncQuery(); items.value = (await adminPropsApi.headlineSlots(filters)).items } catch (caught) { error.value = message(caught) } finally { loading.value = false } }
function reset() { Object.assign(filters, { page: 1, pageSize: 20, keyword: '', status: '', sort: 'createdAt:desc' }); void load() }
async function create() { if (!form.pageCode.trim() || !form.slotCode.trim() || !form.reason.trim()) { error.value = '页面、资源位和创建原因不能为空'; return } error.value = ''; conflict.value = ''; try { await adminPropsApi.createHeadlineSlot({ reason: form.reason.trim(), payload: { pageCode: form.pageCode.trim(), slotCode: form.slotCode.trim(), capacity: form.capacity } }, `r19-slot-create-${Date.now().toString(36)}`); creating.value = false; Object.assign(form, { pageCode: '', slotCode: '', capacity: 1, reason: '' }); await load() } catch (caught) { if (isApiRequestError(caught) && caught.status === 409) { conflict.value = '资源位或排期发生冲突，已重载服务端现状；请核对后再提交。'; await load() } else error.value = message(caught) } }
onMounted(() => { void load() })
</script>
<template><article class="page prop-admin-page"><header class="page-heading"><div><div class="eyebrow">曝光运营</div><h1>资源位与排期</h1><p>查看头条资源位容量和服务端冲突状态。</p></div><div><button class="ghost-button" :disabled="loading" @click="load">刷新数据</button> <button v-if="canWrite" class="primary-button" @click="creating = true">创建资源位</button></div></header><StatusNotice v-if="error" tone="danger" title="操作未完成" :detail="error" />
<section class="order-metrics"><div><span>资源位</span><strong>{{ items.length }}</strong><small>当前筛选</small></div><div><span>开放</span><strong>{{ items.filter((item) => item.status === 'ACTIVE').length }}</strong><small>服务端状态</small></div><div><span>总容量</span><strong>{{ items.reduce((sum, item) => sum + Number(item.quantity || 0), 0) }}</strong><small>当前页容量</small></div><div><span>创建能力</span><strong>{{ canWrite ? '可创建' : '只读' }}</strong><small>按当前权限</small></div></section>
<form class="card order-filters" @submit.prevent="filters.page = 1; load()"><label class="field"><span class="field-label">关键词</span><input v-model="filters.keyword" class="input" maxlength="100" placeholder="页面或资源位" /></label><label class="field"><span class="field-label">状态</span><select v-model="filters.status" class="input"><option value="">全部状态</option><option value="ACTIVE">开放</option><option value="INACTIVE">停用</option></select></label><label class="field"><span class="field-label">排序</span><select v-model="filters.sort" class="input"><option value="createdAt:desc">最近创建</option><option value="updatedAt:desc">最近更新</option><option value="quantity:asc">容量升序</option></select></label><button class="primary-button">查询</button><button class="ghost-button" type="button" @click="reset">重置</button></form>
<section class="card table-card"><div v-if="loading" class="loading-state">正在加载资源位…</div><div v-else-if="!items.length" class="empty-state">暂无符合条件的资源位</div><table v-else class="data-table"><thead><tr><th>页面</th><th>资源位</th><th>容量</th><th>状态</th><th>排期提示</th><th>版本</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ config(item).pageCode || '页面待确认' }}</strong><small>#{{ item.id }}</small></td><td>{{ config(item).slotCode || '资源位待确认' }}</td><td>{{ item.quantity }}</td><td><span class="status-chip" :data-status="item.status">{{ statusLabel(item.status) }}</span></td><td>{{ item.status === 'ACTIVE' ? '按容量接受排期' : '当前不接受排期' }}</td><td>v{{ item.version }}</td></tr></tbody></table></section>
<div v-if="creating" class="dialog-backdrop" @click.self="creating = false"><section class="dialog-card"><header><h2>创建资源位</h2><button class="icon-button" aria-label="关闭" @click="creating = false">×</button></header><StatusNotice v-if="conflict" tone="warning" title="资源冲突" :detail="conflict" /><label class="field"><span class="field-label">页面编码</span><input v-model="form.pageCode" class="input" maxlength="255" /></label><label class="field"><span class="field-label">资源位编码</span><input v-model="form.slotCode" class="input" maxlength="255" /></label><label class="field"><span class="field-label">容量</span><input v-model.number="form.capacity" class="input" type="number" min="1" max="1000" /></label><label class="field"><span class="field-label">创建原因</span><textarea v-model="form.reason" class="input" maxlength="500"></textarea></label><p class="dialog-note">容量和排期冲突以服务端返回为准，创建不会自动扩容现有资源位。</p><footer><button class="ghost-button" @click="creating = false">取消</button><button class="primary-button" @click="create">确认创建</button></footer></section></div>
</article></template>
