#!/usr/bin/env python3
"""Generate R14 backend and Android report-reason catalogs from OpenAPI."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("contracts/openapi.yaml")
JAVA_OUTPUT = Path("services/backend/content/src/main/java/cc/orbexa/hhy/content/R14ChatReportReasonCatalog.java")
KOTLIN_OUTPUT = Path("apps/android/feature/chat/src/main/java/cc/orbexa/hhy/chat/R14ChatReportReasons.kt")


class CatalogError(RuntimeError):
    pass


def load_options(root: Path = ROOT) -> list[dict]:
    document = yaml.safe_load((root / SOURCE).read_text(encoding="utf-8"))
    reason = document["components"]["schemas"]["ChatPostConversationsByIdReportRequest"]["properties"]["reasonCode"]
    options = reason.get("x-hhy-options")
    if not isinstance(options, list) or not options:
        raise CatalogError("reasonCode.x-hhy-options must be a non-empty list")
    expected_keys = {"code", "label", "enabled", "order"}
    normalized: list[dict] = []
    codes: set[str] = set()
    orders: set[int] = set()
    for index, raw in enumerate(options, start=1):
        if not isinstance(raw, dict) or set(raw) != expected_keys:
            raise CatalogError(f"option {index} must contain exactly {sorted(expected_keys)}")
        code, label, enabled, order = raw["code"], raw["label"], raw["enabled"], raw["order"]
        if not isinstance(code, str) or re.fullmatch(r"[A-Z][A-Z0-9_]{1,63}", code) is None:
            raise CatalogError(f"option {index} has invalid code")
        if not isinstance(label, str) or not label.strip() or label != label.strip():
            raise CatalogError(f"option {index} has invalid label")
        if type(enabled) is not bool or type(order) is not int or order < 1:
            raise CatalogError(f"option {index} has invalid enabled/order")
        if code in codes or order in orders:
            raise CatalogError("codes and orders must be unique")
        codes.add(code)
        orders.add(order)
        normalized.append({"code": code, "label": label, "enabled": enabled, "order": order})
    normalized.sort(key=lambda item: item["order"])
    enabled_codes = [item["code"] for item in normalized if item["enabled"]]
    if not enabled_codes:
        raise CatalogError("catalog must contain an enabled option")
    if reason.get("enum") != enabled_codes:
        raise CatalogError("reasonCode.enum must equal enabled x-hhy-options ordered by order")
    return normalized


def render_java(options: list[dict]) -> str:
    rows = ",\n".join(
        f'            new Option("{item["code"]}", "{item["label"]}", {str(item["enabled"]).lower()}, {item["order"]})'
        for item in options
    )
    return f'''package cc.orbexa.hhy.content;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

// Generated by scripts/generate_chat_report_reason_catalog.py. Do not edit.
public final class R14ChatReportReasonCatalog {{
    public record Option(String code, String label, boolean enabled, int order) {{}}

    public static final List<Option> OPTIONS = List.of(
{rows}
    );
    private static final Set<String> ENABLED_CODES = OPTIONS.stream()
            .filter(Option::enabled).map(Option::code).collect(Collectors.toUnmodifiableSet());

    private R14ChatReportReasonCatalog() {{}}

    public static boolean isEnabled(String code) {{
        return code != null && ENABLED_CODES.contains(code);
    }}
}}
'''


def render_kotlin(options: list[dict]) -> str:
    rows = ",\n".join(
        f'    R14ReportReasonOption(code = "{item["code"]}", label = "{item["label"]}")'
        for item in options if item["enabled"]
    )
    return f'''package cc.orbexa.hhy.chat

// Generated by scripts/generate_chat_report_reason_catalog.py. Do not edit.
internal val R14_CHAT_REPORT_REASONS: List<R14ReportReasonOption> = listOf(
{rows},
)
'''


def generate(root: Path = ROOT, *, check: bool) -> list[str]:
    options = load_options(root)
    outputs = {
        JAVA_OUTPUT: render_java(options),
        KOTLIN_OUTPUT: render_kotlin(options),
    }
    drift: list[str] = []
    for relative, expected in outputs.items():
        path = root / relative
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None
        if actual != expected:
            if check:
                drift.append(str(relative).replace("\\", "/"))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8", newline="\n")
    return drift


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        drift = generate(check=args.check)
    except (CatalogError, KeyError, TypeError, yaml.YAMLError) as exc:
        print(f"R14_REPORT_REASON_CATALOG_FAIL {exc}", file=sys.stderr)
        return 2
    if drift:
        print("R14_REPORT_REASON_CATALOG_DRIFT " + ",".join(drift), file=sys.stderr)
        return 1
    print("R14_REPORT_REASON_CATALOG_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
